# version numbers included by the main makefile
# this file is patched by fixver.sh

# DLL filename number for Windows
LIB_VERSION = 21

# Shared library versions for Unix
# todo: this is unused at the moment
shared_version = 2.1.0
shared_major_minor = 2.1
