<language=se>
[file_import_query]
PROPERTIES_OF_IMPORTED_OBJECT "Egenskaper för importerat objekt"
IMPORT_NAME                   "Namn:"
IMPORT_TYPE                   "Typ:"
MATCHING_TYPES                "Matchande_typer"
ALL_TYPES                     "Alla_typer"
DO_IMPORT                     "Importera"
SKIP_IMPORT                   "Importera ej"
YOU_MUST_CHECK_A_TYPE         "Du måste välja någon typ.| OK "
FONT_REQUIRES_BPP_OK          "Fonter kräver 8 bitars färgdjup.| OK "
ENTER_PWD                     "Ange lösen:"
OK                            "#10; ~OK "
CANCEL                        "#27;~Avbryt"
ERROR_IN_PASSWORD_RETRY_CLOSE "Det angivna lösenordet är felaktigt. Försök igen| OK "
REMOVE_PREVIOUS_PWDS         "Radera lösenordslistan"
SAVE_PWD_LOCAL                "Spara lokalt"
SHALL_THE_EXISTING_NN_BE_UPDATED_YES_NO "Ska det befintliga objektet (%s) uppdateras eller ska ett nytt skapas?|Uppdatera|Skapa nytt"
PRETTIFY_NAME                 "Snygga till namn"
RELATIVE_PATH                 "Använd relativ sökväg"

<language=en>
[file_import_query]
PROPERTIES_OF_IMPORTED_OBJECT "Properties of imported object"
IMPORT_NAME                   "Name:"
IMPORT_TYPE                   "Type:"
MATCHING_TYPES                "Matching_types"
ALL_TYPES                     "All_types"
DO_IMPORT                     "Do import"
SKIP_IMPORT                   "Skip import"
YOU_MUST_CHECK_A_TYPE         "You must check at least one type.| OK "
FONT_REQUIRES_BPP_OK          "Fonts can only use 8 bits colour depth.| OK "
ENTER_PWD                     "Enter password:"
OK                            "#10; ~OK "
CANCEL                        "#27;~Cancel"
ERROR_IN_PASSWORD_RETRY_CLOSE "The entered password is incorrect. Try again| OK "
REMOVE_PREVIOUS_PWDS         "Clean pwd list"
SAVE_PWD_LOCAL                "Save local"
SHALL_THE_EXISTING_NN_BE_UPDATED_YES_NO "Shall the existing object (%s) be updated or a new created?|Update|New"
PRETTIFY_NAME                 "Prettify name"
RELATIVE_PATH                 "Use relative path"
<language=pl>
[file_import_query]
PROPERTIES_OF_IMPORTED_OBJECT "Wlasciwosci zaimportowanych obiektow"
IMPORT_NAME                   "Nazwa:"
IMPORT_TYPE                   "Typ:"
MATCHING_TYPES                "zgodne_typy"
ALL_TYPES                     "wszystkie_typy"
DO_IMPORT                     "Importuj"
SKIP_IMPORT                   "Pomin import"
YOU_MUST_CHECK_A_TYPE         "Sprawdz przynajmniej jeden typ.| OK "
FONT_REQUIRES_BPP_OK          "Fonty moga uzywac tylko 8 bitowej glebi koloru.| OK "
ENTER_PWD                     "Wprowadz haslo:"
OK                            "#10; ~OK "
CANCEL                        "#27;~Anuluj"
ERROR_IN_PASSWORD_RETRY_CLOSE "Nieprwaidlowe haslo. sprobuj jeszcze raz| OK "
REMOVE_PREVIOUS_PWDS         "Wyczysc liste hasel"
SAVE_PWD_LOCAL                "Zapisz haslo"
SHALL_THE_EXISTING_NN_BE_UPDATED_YES_NO "Obiekt (%s) ma zostac zaktualizowany czy zapisany jako inny?|Aktualizuj|Zapisz jako inny"
PRETTIFY_NAME                 "lepsza nazwa"
RELATIVE_PATH                 "Relatywna sciezka"

<language=hu>
[file_import_query]
PROPERTIES_OF_IMPORTED_OBJECT "Importált objektum tulajdonságai"
IMPORT_NAME                   "Név:"
IMPORT_TYPE                   "Típus:"
MATCHING_TYPES                "Egyezõ típusok"
ALL_TYPES                     "Minden típus"
DO_IMPORT                     "Importál"
SKIP_IMPORT                   "Importálás kihagyása"
YOU_MUST_CHECK_A_TYPE         "Legalább egy típust ki kell jelölni.| OK "
FONT_REQUIRES_BPP_OK          "betûk csak 8 bites színmélységûek lehetnek.| OK "
ENTER_PWD                     "Jelszó:"
OK                            "#10; ~OK "
CANCEL                        "#27;~Mégsem"
ERROR_IN_PASSWORD_RETRY_CLOSE "helytelen jelszó. Próbálja újra| OK "
REMOVE_PREVIOUS_PWDS         "Jelszólista törlése"
SAVE_PWD_LOCAL                "Helyi mentés"
SHALL_THE_EXISTING_NN_BE_UPDATED_YES_NO "A létezõ (%s) objektumot frissítsük, vagy újat készítsünk?|Frissít|Új"
PRETTIFY_NAME                 "Név szépítése"
RELATIVE_PATH                 "Relatív útvonal használata"

<language=es>
[file_import_query]
PROPERTIES_OF_IMPORTED_OBJECT "Propiedades del objeto importado"
IMPORT_NAME                   "Nombre:"
IMPORT_TYPE                   "Tipo:"
MATCHING_TYPES                "Tipos_asociados"
ALL_TYPES                     "Todos_los tipos"
DO_IMPORT                     "Importar"
SKIP_IMPORT                   "Saltar importación"
YOU_MUST_CHECK_A_TYPE         "Debes seleccionar al menos un tipo.| Aceptar "
FONT_REQUIRES_BPP_OK          "Las fuentes solo pueden usar una profundidad de color de 8 bits.| Aceptar "
ENTER_PWD                     "Introduce el password:"
OK                            "#10; ~Aceptar "
CANCEL                        "#27;~Cancelar"
ERROR_IN_PASSWORD_RETRY_CLOSE "El password introducido es incorrecto. Inténtalo de nuevo| Aceptar "
REMOVE_PREVIOUS_PWDS         "Limpiar lista de pwds"
SAVE_PWD_LOCAL                "Salvar local"
SHALL_THE_EXISTING_NN_BE_UPDATED_YES_NO "¿Se deben actualizar el objeto existente (%s), o se debe crear uno nuevo?|Actualizar|Nuevo"
PRETTIFY_NAME                 "Mejorar apariencia del nombre"
RELATIVE_PATH                 "Usar ruta relativa"

<language=fr>
[file_import_query]
PROPERTIES_OF_IMPORTED_OBJECT "Propiétés de l'objet importé"
IMPORT_NAME                   "Nom:"
IMPORT_TYPE                   "Type:"
MATCHING_TYPES                "Types_associés"
ALL_TYPES                     "Tous_les_types"
DO_IMPORT                     "Importer"
SKIP_IMPORT                   "Shunter importation"
YOU_MUST_CHECK_A_TYPE         "Vous devez choisir au moins un type.| Accepter "
FONT_REQUIRES_BPP_OK          "Les polices ne peuvent utiliser qu'une profondeur de couleur de 8 bits.| Accepter "
ENTER_PWD                     "Introduisez le mot de passe:"
OK                            "#10; ~Accepter "
CANCEL                        "#27; ~Annuler"
ERROR_IN_PASSWORD_RETRY_CLOSE "Le mot de passe introduit est incorrect. Essayez à nouveau| Accepter "
REMOVE_PREVIOUS_PWDS         "Vider la liste de mots de passe"
SAVE_PWD_LOCAL                "Sauvegarder local"
SHALL_THE_EXISTING_NN_BE_UPDATED_YES_NO "L'objet existant (%s) doit être actualisé, ou doit-on en créer un nouveau?|Actualiser|Nouveau"
PRETTIFY_NAME                 "Améliorer l'apparence du nom"
RELATIVE_PATH                 "Utiliser chemin relatif"

<language=pt>
[file_import_query]
PROPERTIES_OF_IMPORTED_OBJECT "Propriedades do objeto importado"
IMPORT_NAME                   "Nome:"
IMPORT_TYPE                   "Tipo:"
MATCHING_TYPES                "Tipos_Associados"
ALL_TYPES                     "Todos_Tipos"
DO_IMPORT                     "Importar"
SKIP_IMPORT                   "Pular importação"
YOU_MUST_CHECK_A_TYPE         "Voce deve selecionar pelo menos um tipo.| Aceitar"
FONT_REQUIRES_BPP_OK          "As fontes podem usar somente 8 bits de profundidade.| Aceitar"
ENTER_PWD                     "Entre com a senha:"
OK                            "#10; ~Aceitar "
CANCEL                        "#27;~Cancelar"
ERROR_IN_PASSWORD_RETRY_CLOSE "A senha informada esta incorreta. Tente novamente| Aceitar"
REMOVE_PREVIOUS_PWDS         "Limpar a lista de Pwds"
SAVE_PWD_LOCAL                "Salvar local"
SHALL_THE_EXISTING_NN_BE_UPDATED_YES_NO "Deseja atualizar o objeto existente (%s) ou criar um novo?|Atualizar|Novo"
PRETTIFY_NAME                 "Deseja melhorar a aparência do nome"
RELATIVE_PATH                 "Usar caminho parecido"
