<language = se>
[filebrow]
DEVICE            "Enhet:"
SHOW              "Visa:"
LABEL_CANCEL      "#27;~Avbryt"
FILE_ERROR        "Ogiltig fil|~OK"
SELECTED_FILE     "Vald:"
CREATE_DIRECTORY  "Skapa underkatalog"
CREATE_DATAFILE   "Skapa en Allegro datafil"
SETTINGS          "#settings;Anpassa"
SURE_YOU_WANT_TO_REMOVE_DIRECTORY_NN_OK_CANCEL  "Är du säker på att du vill ta bort katalogen \"%s\" (allt som eventuellt finns i den kommer "
                                                "också att tas bort)?|Ta bort|Avbryt"
SURE_YOU_WANT_TO_REMOVE_FILE_NN_OK_CANCEL       "Är du säker på att du vill ta bort filen \"%s\"|Ta bort|Avbryt"
YES_TO_ALL        "|Ja till_alla"
DELETE_FILE_ERROR_CONTINUE "Borttagande av filobjektet har inte fullföljts|Fortsätt"
NN_IS_A_DIRECTORY "%s är en katalog|Stäng"
NN_IS_NO_DIRECTORY "%s är inte en katalog|Stäng"
NN_NOT_EXISTS_RETRY_CLOSE "%s finns inte. Försök igen|Stäng"
NN_ALREADY_EXISTS_OK_CANCEL "%s finns redan, är du verkligen säker?|Japp|Avbryt"
NN_ALREADY_EXISTS_CLOSE "%s finns redan, försök igen.|OK"
OPEN_NEW_BROWSER  "Öppna ny fil-bläddrare"
DEFAULT_WINLABEL  "CGUI:s filväljare"
MANAGER_WINLABEL  "CGUI:s filövervakare"
DEFAULT_BUTLABEL  "OK"
EDIT_FILE         "Byt namn"
COPY_FILE         "Kopiera fil"
CUT_FILE          "Klipp ut fil"
DELETE_FILE       "Ta bort"
PASTE_FILE        "Klistra in"
SELECT            "Välj"
SHOW_IMAGE        "Visa bild"
SHOW_PREVIEW_WINDOW "Förhandsgranskning"
SHOW_ORIGINAL     "Visa originalplats"
SHOW_TIME         "Visa ändringstid"
SHOW_SIZE         "Visa storlek"
SHOW_ATTRIB       "Visa attribut"
SHOW_PERM         "Visa rättigheter"
SHOW_HS           "Visa gömda-/systemfiler"
SHOW_BUFFER       "Visa kopieringsbuffert"
FORCE_CASE        "Formatterade namn"
NO_NAME           "Namn saknas"
ERROR_MESSAGE     "Felmeddelande"
INCOMPLETE_DIR_LIST_CLOSE "Den visade filkatalogen kan vara ofullständig pga okänt fel.|Stäng"
<start=COLUMN_LABELS>
   L_ICON            ""
   L_NAME            "Namn"
   L_TIME            "Ändrad"
   L_SIZE            "Storlek(k)"
   L_ATTRIB          "Attrib"
<end=NR_COLUMN_LABELS>
<start=COLUMN_LABELS_U>
   _           ""
   _           "Namn"
   _           "Ändrad"
   _           "Storlek(k)"
   _           "Rättigheter"
<end=NR_COLUMN_LABELS_U>
FB_TXT_DIR         "katalog"
FB_TXT_DIRS        "kataloger"
FB_TXT_FILE        "fil"
FB_TXT_FILES       "filer"
FB_TEXT_MB         "MB"
FB_TEXT_KB         "kB"
FB_TEXT_BYTE       "bytes"
LOCATION          "Plats:"
FILE_ACTION       "Kör"
ENTER_PASSWORD    "Ange lösen"

<language=en>
[filebrow]
DEVICE            "Disk device:"
SHOW              "Show:"
LABEL_CANCEL      "#27;~Cancel"
FILE_ERROR        "Illegal file|~OK"
SELECTED_FILE     "Selected:"
CREATE_DIRECTORY  "Create sub directory"
CREATE_DATAFILE   "Create Allegro data file"
SETTINGS          "#settings;Settings"
SURE_YOU_WANT_TO_REMOVE_DIRECTORY_NN_OK_CANCEL  "Are you sure that you want to remove the directory \"%s\" (all that may be stored in it will be deleted)?|Yes| No "
SURE_YOU_WANT_TO_REMOVE_FILE_NN_OK_CANCEL       "Are you sure that you want to remove the file \"%s\".|Yes| No "
YES_TO_ALL        "|Yes_to all"
DELETE_FILE_ERROR_CONTINUE "The removing of the disk object is not fulfilled|Continue"
NN_IS_A_DIRECTORY "%s is a directory|Close"
NN_IS_NO_DIRECTORY "%s is no directory|Close"
NN_NOT_EXISTS_RETRY_CLOSE "%s does not not exist. Try again.|Close"
NN_ALREADY_EXISTS_OK_CANCEL "%s does already exist, are you really sure?|Yes|Cancel"
NN_ALREADY_EXISTS_CLOSE "%s does already exist, please try again|OK"
OPEN_NEW_BROWSER  "Open new file-browser"
DEFAULT_WINLABEL  "CGUI file-selector"
MANAGER_WINLABEL  "CGUI file-manager"
DEFAULT_BUTLABEL  "OK"
EDIT_FILE         "Edit properties"
COPY_FILE         "Copy file"
CUT_FILE          "Cut file"
DELETE_FILE       "Delete"
PASTE_FILE        "Paste"
SELECT            "Select"
SHOW_IMAGE        "Show image"
SHOW_PREVIEW_WINDOW "Preview window"
SHOW_ORIGINAL     "Show original place"
SHOW_TIME         "Show update time"
SHOW_SIZE         "Show size"
SHOW_ATTRIB       "Show attributes"
SHOW_PERM         "Show permissions"
SHOW_HS           "Show hidden/system files"
SHOW_BUFFER       "Show copy buffer"
FORCE_CASE        "Formatted names"
NO_NAME           "No name present"
ERROR_MESSAGE     "Error message"
INCOMPLETE_DIR_LIST_CLOSE "The directory listing may be incomplete due to and unknown error|OK"
<start=COLUMN_LABELS>
   L_ICON            ""
   L_NAME            "Name"
   L_TIME            "Changed"
   L_SIZE            "Size(k)"
   L_ATTRIB          "Attrib"
<end=NR_COLUMN_LABELS>
<start=COLUMN_LABELS_U>
   _           ""
   _           "Name"
   _           "Changed"
   _           "Size(k)"
   _           "Permissions"
<end=NR_COLUMN_LABELS_U>
FB_TXT_DIR         "dir"
FB_TXT_DIRS        "dirs"
FB_TXT_FILE        "file"
FB_TXT_FILES       "files"
FB_TEXT_MB         "MB"
FB_TEXT_KB         "kB"
FB_TEXT_BYTE       "bytes"
LOCATION          "Location:"
FILE_ACTION       "Action"
ENTER_PASSWORD    "Enter password"
<language=pl>
[filebrow]
DEVICE            "Naped:"
SHOW              "Pokaz:"
LABEL_CANCEL      "#27;~Anuluj"
FILE_ERROR        "Niepoprawny plik|~OK"
SELECTED_FILE     "Zaznaczone:"
CREATE_DIRECTORY  "Stworz folder"
CREATE_DATAFILE   "Stworz Allegro data file"
SETTINGS          "#settings;Ustawienia"
SURE_YOU_WANT_TO_REMOVE_DIRECTORY_NN_OK_CANCEL  "Czy na pewno usunac folder \"%s\" ? |Tak| Nie "
SURE_YOU_WANT_TO_REMOVE_FILE_NN_OK_CANCEL       "Czy na pewno usunac plik \"%s\".|Tak| Nie "
YES_TO_ALL        "|Tak na wszystkie"
DELETE_FILE_ERROR_CONTINUE "Blad usuwania pliku|Kontynuuj"
NN_IS_A_DIRECTORY "%s jest folderem|Zamknij"
NN_IS_NO_DIRECTORY "%s NIE jest folderem|Zamknij"
NN_NOT_EXISTS_RETRY_CLOSE "%s nie istnieje. sprobuj ponownie.|Zamknij"
NN_ALREADY_EXISTS_OK_CANCEL "%s juz istnieje, czy kontynuowac?|Tak|Anuluj"
NN_ALREADY_EXISTS_CLOSE "%s juz istnieje. sprobuj ponownie.|OK"
OPEN_NEW_BROWSER  "Otworz nowa przegladarke"
DEFAULT_WINLABEL  "CGUI - wybor pliku"
MANAGER_WINLABEL  "CGUI - manager plikow"
DEFAULT_BUTLABEL  "OK"
EDIT_FILE         "Wlasciwosci"
COPY_FILE         "Kopiuj"
CUT_FILE          "Wytnij"
DELETE_FILE       "Usun"
PASTE_FILE        "Wklej"
SELECT            "Wybierz"
SHOW_IMAGE        "Pokaz obraz"
SHOW_PREVIEW_WINDOW     "Okno podgladu"
SHOW_ORIGINAL     "Pokaz orignalna sciezke"
SHOW_TIME         "Pokaz czas modyfikacji"
SHOW_SIZE         "Pokaz rozmiar"
SHOW_ATTRIB        "Pokaz atrybuty"
SHOW_PERM          "Pokaz uprawnienia"
SHOW_HS            "Pokaz pliki ukryte/systemowe"
SHOW_BUFFER        "Pokaz bufor kopiowania"
FORCE_CASE        "przeformatowane nazwy"
NO_NAME           "brak nazwy"
ERROR_MESSAGE     "Informacja o bledzie"
INCOMPLETE_DIR_LIST_CLOSE "Wypis zawartosci folderu moze byc niekompletny z powodu nieznanego bledu|OK"
<start=COLUMN_LABELS>
   L_ICON            ""
   L_NAME            "Nazwy"
   L_TIME            "Zmieniony"
   L_SIZE            "Rozmiar(k)"
   L_ATTRIB          "Atryb."
<end=NR_COLUMN_LABELS>
<start=COLUMN_LABELS_U>
   _           ""
   _           "Nazwy"
   _           "Zmieniony"
   _           "Rozmiar(k)"
   _           "Permissions"
<end=NR_COLUMN_LABELS_U>
FB_TXT_DIR         "dir"
FB_TXT_DIRS        "dirs"
FB_TXT_FILE        "Plik"
FB_TXT_FILES       "Pliki"
FB_TEXT_MB         "MB"
FB_TEXT_KB         "kB"
FB_TEXT_BYTE       "bajtow"
LOCATION          "Lokacja:"
FILE_ACTION       "Akacja"
ENTER_PASSWORD    "Wprowadz haslo"

<language=hu>
[filebrow]
DEVICE            "Lemez eszköz:"
SHOW              "Mutat:"
LABEL_CANCEL      "#27;~Mégsem"
FILE_ERROR        "Érvénytelen fájl|~OK"
SELECTED_FILE     "Kiválasztva:"
CREATE_DIRECTORY  "Alkönyvtár készítése"
CREATE_DATAFILE   "Allegro data fájl készítése"
SETTINGS          "#settings;Beállítások"
SURE_YOU_WANT_TO_REMOVE_DIRECTORY_NN_OK_CANCEL  "Biztos benne,hogy el akarja távolítani a \"%s\" könyvtárat (minden tartalma törlésre kerül)?|Igen| Nem "
SURE_YOU_WANT_TO_REMOVE_FILE_NN_OK_CANCEL       "Biztos benne, hogy el akarja távolítani a \"%s\ fájlt?\".|Igen| Nem "
YES_TO_ALL        "|Igen mindenre"
DELETE_FILE_ERROR_CONTINUE "A lemez objektum eltávolítása nem sikerült|Folytatás"
NN_IS_A_DIRECTORY "%s egy könyvtár|Bezárás"
NN_IS_NO_DIRECTORY "%s nem könyvtár|Bezárás"
NN_NOT_EXISTS_RETRY_CLOSE "%s nem létezik. Próbálja újra.|Bezárás"
NN_ALREADY_EXISTS_OK_CANCEL "%s már létezik, biztos benne?|Igen|Mégsem"
NN_ALREADY_EXISTS_CLOSE "%s már létezik, próbálja újra|OK"
OPEN_NEW_BROWSER  "Új fájl böngészõ megnyitása"
DEFAULT_WINLABEL  "CGUI fájl kiválasztó"
MANAGER_WINLABEL  "CGUI fájlkezelõ"
DEFAULT_BUTLABEL  "OK"
EDIT_FILE         "Tulajdonságok szerkesztése"
COPY_FILE         "Fájl másolás"
CUT_FILE          "Fájl kivágás"
DELETE_FILE       "Törlés"
PASTE_FILE        "Beillesztés"
SELECT            "Kiválaszt"
SHOW_IMAGE        "Kép mutatása"
SHOW_PREVIEW_WINDOW "Elõnézet"
SHOW_ORIGINAL     "Eredeti hely mutatása"
SHOW_TIME         "Módosítási idõ mutatása"
SHOW_SIZE         "Méret mutatása"
SHOW_ATTRIB       "Attributumok mutatása"
SHOW_PERM         "Jogosultságok mutatása"
SHOW_HS           "Rejtett és rendszerfájlok mutatása"
SHOW_BUFFER       "Másolási tár mutatása"
FORCE_CASE        "Formázott nevek"
NO_NAME           "Nincs név"
ERROR_MESSAGE     "Hibaüzenet"
INCOMPLETE_DIR_LIST_CLOSE "A könyvtárlista hiányos lehet ismeretlen hiba miatt|OK"
<start=COLUMN_LABELS>
   L_ICON            ""
   L_NAME            "Név"
   L_TIME            "Változtatva"
   L_SIZE            "Méret(k)"
   L_ATTRIB          "Tulajd."
<end=NR_COLUMN_LABELS>
<start=COLUMN_LABELS_U>
   _           ""
   _           "Név"
   _           "Változtatva"
   _           "Méret(k)"
   _           "Jogosultság"
<end=NR_COLUMN_LABELS_U>
FB_TXT_DIR         "könyvtár"
FB_TXT_DIRS        "könyvtárak"
FB_TXT_FILE        "fájl"
FB_TXT_FILES       "fájlok"
FB_TEXT_MB         "MB"
FB_TEXT_KB         "kB"
FB_TEXT_BYTE       "bájt"
LOCATION          "Hely:"
FILE_ACTION       "Mûvelet"
ENTER_PASSWORD    "Jelszó beírása"

<language=es>
[filebrow]
DEVICE            "Unidad:"
SHOW              "Mostrar:"
LABEL_CANCEL      "#27;~Cancelar"
FILE_ERROR        "Archivoilegal|~Aceptar"
SELECTED_FILE     "Seleccionado:"
CREATE_DIRECTORY  "Crear subdirectorio"
CREATE_DATAFILE   "Crear archivo de datos de Allegro"
SETTINGS          "#settings;Configuración"
SURE_YOU_WANT_TO_REMOVE_DIRECTORY_NN_OK_CANCEL  "¿Estás seguro de que quieres eliminar el directorio \"%s\" (todo lo que esté guardado en él será eliminado)?|Sí| No "
SURE_YOU_WANT_TO_REMOVE_FILE_NN_OK_CANCEL       "¿Estás seguro de que quieres eliminar el archivo \"%s\"?|Sí| No "
YES_TO_ALL        "|Sí a todo"
DELETE_FILE_ERROR_CONTINUE "La eliminadióc del objeto no se ha completado|Continuar"
NN_IS_A_DIRECTORY "%s es un directorio|Cerrar"
NN_IS_NO_DIRECTORY "%s no es un directorio|Cerrar"
NN_NOT_EXISTS_RETRY_CLOSE "%s no existe. Inténtalo de nuevo.|Cerrar"
NN_ALREADY_EXISTS_OK_CANCEL "%s ya existe, estás seguro?|Sí|Cancelar"
NN_ALREADY_EXISTS_CLOSE "%s ya existe, inténtalo de nuevo|Aceptar"
OPEN_NEW_BROWSER  "Abrir nuevo navegador"
DEFAULT_WINLABEL  "Selector de archivos de CGUI"
MANAGER_WINLABEL  "Gestor de archivos de CGUI"
DEFAULT_BUTLABEL  "Aceptar"
EDIT_FILE         "Editar propiedades"
COPY_FILE         "Copiar archivo"
CUT_FILE          "Cortar archivo"
DELETE_FILE       "Eliminar"
PASTE_FILE        "Pegar"
SELECT            "Seleccionar"
SHOW_IMAGE        "Mostrar imagen"
SHOW_PREVIEW_WINDOW "Ventana de previsualización"
SHOW_ORIGINAL     "Mostrar lugar original"
SHOW_TIME         "Mostrar tiempo de modificación"
SHOW_SIZE         "Mostrar tamaño"
SHOW_ATTRIB       "Mostrar atributos"
SHOW_PERM         "Mostrar permisos"
SHOW_HS           "Mostrar archivos ocultos/de sistema"
SHOW_BUFFER       "Mostrar búffer de copia"
FORCE_CASE        "Nombres formateados"
NO_NAME           "Nombre no presente"
ERROR_MESSAGE     "Mensaje de error"
INCOMPLETE_DIR_LIST_CLOSE "El listado del directorio puede estar incompleto debido a un error desconocido|Aceptar"
<start=COLUMN_LABELS>
   L_ICON            ""
   L_NAME            "Nombre"
   L_TIME            "Modificado"
   L_SIZE            "Tamaño(k)"
   L_ATTRIB          "Atrib."
<end=NR_COLUMN_LABELS>
<start=COLUMN_LABELS_U>
   _           ""
   _           "Nombre"
   _           "Modificado"
   _           "Tamaño(k)"
   _           "Permisos"
<end=NR_COLUMN_LABELS_U>
FB_TXT_DIR         "dir"
FB_TXT_DIRS        "dirs"
FB_TXT_FILE        "arch"
FB_TXT_FILES       "archs"
FB_TEXT_MB         "MB"
FB_TEXT_KB         "kB"
FB_TEXT_BYTE       "bytes"
LOCATION          "Dirección:"
FILE_ACTION       "Acción"
ENTER_PASSWORD    "Introduce el password"

<language=fr>
[filebrow]
DEVICE            "Disque:"
SHOW              "Montrer:"
LABEL_CANCEL      "#27;~Annuler"
FILE_ERROR        "Fichier illegal|~Accepter"
SELECTED_FILE     "Selectionné:"
CREATE_DIRECTORY  "Créer sous-répertoire"
CREATE_DATAFILE   "Créer fichier de données d'Allegro"
SETTINGS          "#settings;Configuration"
SURE_YOU_WANT_TO_REMOVE_DIRECTORY_NN_OK_CANCEL  "Etes vous sûr de voiloir éliminer le répertoire\"%s\" (tout son contenu sera perdu)?|Oui| Non "
SURE_YOU_WANT_TO_REMOVE_FILE_NN_OK_CANCEL       "Etes vous sûr de voiloir éliminer le fichier\"%s\" ?|Oui| Non "
YES_TO_ALL        "|Oui à tout"
DELETE_FILE_ERROR_CONTINUE "L'élimination de l'objet n'a pas été complétée|Continuer"
NN_IS_A_DIRECTORY "%s est un répertoire|Fermer"
NN_IS_NO_DIRECTORY "%s n'est pas un répertoire|Fermer"
NN_NOT_EXISTS_RETRY_CLOSE "%s n'existe pas. Essayez à nouveau.|Fermer"
NN_ALREADY_EXISTS_OK_CANCEL "%s existe, êtes vous sûr?|Oui|Annuler"
NN_ALREADY_EXISTS_CLOSE "%s existe, essayez à nouveau|Accepter"
OPEN_NEW_BROWSER  "Ouvrir un nouveau navigateur"
DEFAULT_WINLABEL  "Selecteur de fichiers de CGUI"
MANAGER_WINLABEL  "Manager de fichiers de CGUI"
DEFAULT_BUTLABEL  "Accepter"
EDIT_FILE         "Editer propriétés"
COPY_FILE         "Copier fichier"
CUT_FILE          "Couper fichier"
DELETE_FILE       "Eliminer"
PASTE_FILE        "Coller"
SELECT            "Selectionner"
SHOW_IMAGE        "Montrer image"
SHOW_PREVIEW_WINDOW "Fenêtre de prévisualisation"
SHOW_ORIGINAL     "Montrer emplacement originel"
SHOW_TIME         "Montrer date de modification"
SHOW_SIZE         "Montrer taille"
SHOW_ATTRIB       "Montrer attributs"
SHOW_PERM         "Montrer droits"
SHOW_HS           "Montrer fichiers cachés/de système"
SHOW_BUFFER       "Montrer buffer de copie"
FORCE_CASE        "Noms formattés"
NO_NAME           "Nom non présent"
ERROR_MESSAGE     "Message d'erreur"
INCOMPLETE_DIR_LIST_CLOSE "Le listing du répertoire peut être incomplet à cause d'une erreur inconnue|Accepter"
<start=COLUMN_LABELS>
   L_ICON            ""
   L_NAME            "Nom"
   L_TIME            "Modifié"
   L_SIZE            "Taille(k)"
   L_ATTRIB          "Attrib."
<end=NR_COLUMN_LABELS>
<start=COLUMN_LABELS_U>
   _           ""
   _           "Nom"
   _           "Modifié"
   _           "Taille(k)"
   _           "Droits"
<end=NR_COLUMN_LABELS_U>
FB_TXT_DIR         "rep"
FB_TXT_DIRS        "reps"
FB_TXT_FILE        "fich"
FB_TXT_FILES       "fichs"
FB_TEXT_MB         "Mo"
FB_TEXT_KB         "ko"
FB_TEXT_BYTE       "octets"
LOCATION          "Addresse:"
FILE_ACTION       "Action"
ENTER_PASSWORD    "Introduisez le mot de passe"

<language=pt>
[filebrow]
DEVICE            "Unidade:"
SHOW              "Mostrar:"
LABEL_CANCEL      "#27;~Cancelar"
FILE_ERROR        "Arquivo ilegal|~/Aceitar"
SELECTED_FILE     "Selecionado:"
CREATE_DIRECTORY  "Criar sub-diretório"
CREATE_DATAFILE   "Criar arquivo de dados do Allegro"
SETTINGS          "#configurações;Configurações"
SURE_YOU_WANT_TO_REMOVE_DIRECTORY_NN_OK_CANCEL  "Você realmente quer remover o diretório \"%s\" (tudo que esta armazenado será deletado)?|Sim| Não "
SURE_YOU_WANT_TO_REMOVE_FILE_NN_OK_CANCEL       "Você realmente quer remover o arquivo\"%s\".|Sim| Não "
YES_TO_ALL        "|Sim para todos"
DELETE_FILE_ERROR_CONTINUE "A remoção do objeto do disco não foi completada|Continuar"
NN_IS_A_DIRECTORY "%s é um diretório|Fechar"
NN_IS_NO_DIRECTORY "%s não é um diretório|Fechar"
NN_NOT_EXISTS_RETRY_CLOSE "%s não existe. Tente novamente.|Fechar"
NN_ALREADY_EXISTS_OK_CANCEL "%s já existe, você realmente está certo dessa operação?|Sim|Cancelar"
NN_ALREADY_EXISTS_CLOSE "%s já existe, por favor tente novamente|Aceitar"
OPEN_NEW_BROWSER  "Abrir novo navegador"
DEFAULT_WINLABEL  "Selecionador de arquivos CGUI"
MANAGER_WINLABEL  "Gestor de arquivos CGUI"
DEFAULT_BUTLABEL  "Aceitar"
EDIT_FILE         "Editar propriedades"
COPY_FILE         "Copiar arquivo"
CUT_FILE          "Recortar arquivo"
DELETE_FILE       "Deletar"
PASTE_FILE        "Colar"
SELECT            "Selecionar"
SHOW_IMAGE        "Mostrar imagem"
SHOW_PREVIEW_WINDOW "Janela de pré-visualização"
SHOW_ORIGINAL     "Mostrar lugar original"
SHOW_TIME         "Mostrar data de atualização"
SHOW_SIZE         "Mostrar tamanho"
SHOW_ATTRIB       "Mostrar atributos"
SHOW_PERM         "Mostrar permissões"
SHOW_HS           "Mostrar arquivos ocultos/de sistema"
SHOW_BUFFER       "Mostrar buffer de cópia"
FORCE_CASE        "Nomes formatados"
NO_NAME           "Nenhum nome presente"
ERROR_MESSAGE     "Mensagem de erro"
INCOMPLETE_DIR_LIST_CLOSE "A lista do diretório pode estar incompleta devido a um erro desconhecido|Aceitar"
<start=COLUMN_LABELS>
   L_ICON            ""
   L_NAME            "Nome"
   L_TIME            "Modificado"
   L_SIZE            "Tamanho(k)"
   L_ATTRIB          "Atributo"
<end=NR_COLUMN_LABELS>
<start=COLUMN_LABELS_U>
   _           ""
   _           "Nome"
   _           "Modificado"
   _           "Tamanho(k)"
   _           "Permissões"
<end=NR_COLUMN_LABELS_U>
FB_TXT_DIR         "diretório"
FB_TXT_DIRS        "diretórios"
FB_TXT_FILE        "arquivo"
FB_TXT_FILES       "arquivos"
FB_TEXT_MB         "MB"
FB_TEXT_KB         "kB"
FB_TEXT_BYTE       "bytes"
LOCATION          "Localização:"
FILE_ACTION       "Ação"
ENTER_PASSWORD    "Entre com a senha"
