<language = se>
[filedial]
PERMISSIONS_SET_ERROR "Det är inte tillåtet för dig att ändra rättigheterna| OK "
MODE_MASK         "Flaggor: "
PERMISSIONS       "Rättigheter"
<start=USER_CAT>
 _ "Ägare:"
 _ "Grupp:"
 _ "Andra:"
<end=NR_USER_CAT>
<start=ACCESS_TYPE>
 _ "Läsa"
 _ "Skriva"
 _ "Exekvera"
<end=NR_ACCESS_TYPE>
EDIT_DISK_OBJECT  "Redigera diskobjekt"
LOCATION          "Plats:"
NAME              "Namn:"
FILE_ACTION       "Kör"
SIZE              "Storlek:"
DATE              "Senast ändrad:"
UNKNOWN           "Okänt"
DAT_SOURCE        "Ursprungsnamn:"
FILETYPE          "Typ av fil:"
ALLEGRO_SUBDIR    "Allegro datafil, underkatalog"
ALLEGRO_SOUND     "Allegro ljudinspelning"
ALLEGRO_MIDI      "Allegro midi fil"
ALLEGRO_MIDI_PAT  "Allegro midi fil"
ALLEGRO_ANIMATION "Allegro animation"
ALLEGRO_BITMAP    "Allegro bild"
ALLEGRO_RLE       "Allegro sprite"
ALLEGRO_CMP       "Allegro kompilerad sprite"
ALLEGRO_CMPX      "Allegro mode-x kompilerad sprite"
ALLEGRO_PAL       "Allegro palett"
ALLEGRO_FONT      "Allegro font"
ALLEGRO_BINARY    "Allegro binärfil"
ALLEGRO_USER      "Allegro tillämpningsspecifikt objekt"
ALLEGRO_DAT       "Allegro datafil"
DIRECTORY_TEXT    "Filkatalog"
FILE_TEXT         "Fil"
IMAGE             "Bild"
ATTRIBUTE         "Attribut"
READ_ONLY         "~R (Skrivskyddad)"
HIDDEN            "~H (Dold)"
SYSTEM            "~S (Systemfil)"
ARCHIVE           "~A (Arkivfil)"
ATTRIB_ERROR_CLOSE_NN "Kommandot att ändra på attribut misslyckades. Meddelandet från systemet lyder:\"%s\"|Stäng"
ATTRIB_ERROR_UNKNOWN_CLOSE "Kommandot att ändra på attribut misslyckades av okänd anledning.|Stäng"
PACKED            "Packning:"
NONE              "Ingen"
INDIVIDUAL        "Individuell"
GLOBAL            "Global"
SPECIFIED_DIRECTORY_NOT_CREATED_CLOSE "Den angivna katalogen kan inte skapas|#27;Stäng"
CREATE_DIRECTORY  "Skapa katalog"
CREATE_SUBDATAFILE "Skapa nästlad datafil"
CREATE_DATAFILE   "Skapa ny datafil"
MAKE_DATAFILE     "Allegro datafil"
LABEL_OK          " OK "
LABEL_CANCEL      "#27;~Avbryt"
NEW_PWD_REMOVE_PREV_YES_NO "Datafilen har nu sparats med det nya lösenordet._Ska det gamla lösenordet glömmas?| Ja |Nej"
NO_PWD_REMOVE_PREV_YES_NO "Datafilen har nu sparats utan lösenordet._Ska det tidigare lösenordet glömmas?| Ja |Nej"
NEW_PWD_ADD_REPLACE        "Datafilen har nu sparats med det nya lösenordet._Ska det tidigare använda lösenordet glömmas eller ska båda behållas i minnet?|Behåll_båda|Glöm"
SAVE_PASSWORD     "Spara lösen lokalt"
DATAFILE_PROPERTIES "Datafilsegenskaper"
PASSWORD          "Lösenord"
CLEAN_PREV_PWD    "Radera lösenordslistan"
UPDATE_OBJECTS    "Uppdatera objekten"
SCALED_IMAGE      "(skalad)"
VIEW_IMAGE        "Visa full storlek"
DATAFILE_OBJECT   "Datafilobjekt"
PROPERTY_LIST     "Egenskapslista"
NEW_PROPERTY      "Ny egenskap"
HEADER_FILES      "H-fil generering"
HEADER_FILE_NAME  "Fil namn:"
BROWSE            "Bläddra..."
MACRO_PREFIX      "Makro prefix (valfri):"
DO_GENERATE       "Generera filen!"
FAILED_IN_HEADER_GENERATION_CLOSE "Genereringen misslyckades|Stäng"
USE_PALETTE       "Använd paletten"
UNIMPLEMENTED_VIEWER "Denna objekttyp saknar visningsfunktion"
SELECT_HEADER_FILE "Ange namn för h-filen"
SELECT             "Välj"

<language = en>
[filedial]
PERMISSIONS_SET_ERROR "You are not allowed to change the permissions| OK "
MODE_MASK         "Flags: "
PERMISSIONS       "Permissions "
<start=USER_CAT>
 _ "Owner:"
 _ "Group:"
 _ "Other:"
<end=NR_USER_CAT>
<start=ACCESS_TYPE>
 _ "Read"
 _ "Write"
 _ "Execute"
<end=NR_ACCESS_TYPE>
EDIT_DISK_OBJECT  "Edit disk object"
LOCATION          "Location:"
NAME              "Name:"
FILE_ACTION       "Action"
SIZE              "Size:"
DATE              "Latest change at:"
UNKNOWN           "Unknown"
DAT_SOURCE        "Source-name:"
FILETYPE          "Type of file:"
ALLEGRO_SUBDIR    "Allegro datafile (directory)"
ALLEGRO_SOUND     "Allegro sound sample"
ALLEGRO_MIDI      "Allegro midi file"
ALLEGRO_MIDI_PAT  "Allegro midi file"
ALLEGRO_ANIMATION "Allegro animation"
ALLEGRO_BITMAP    "Allegro image"
ALLEGRO_RLE       "Allegro sprite"
ALLEGRO_CMP       "Allegro compiled sprite"
ALLEGRO_CMPX      "Allegro mode-x compiled sprite"
ALLEGRO_PAL       "Allegro palette"
ALLEGRO_FONT      "Allegro font"
ALLEGRO_BINARY    "Allegro binary file"
ALLEGRO_USER     "Allegro user-defined"
ALLEGRO_DAT   "Allegro datafile"
DIRECTORY_TEXT    "Directory"
FILE_TEXT         "File"
IMAGE             "Image"
ATTRIBUTE         "Attributes"
READ_ONLY         "~R (Write protected)"
HIDDEN            "~H (Hidden)"
SYSTEM            "~S (System file)"
ARCHIVE           "~A (Archive file)"
ATTRIB_ERROR_CLOSE_NN "The command to change attribute failed. The message from the system is:\"%s\"|Close"
ATTRIB_ERROR_UNKNOWN_CLOSE "The command to change attribute failed for unknown reasons.|Close"
PACKED             "Packing:"
NONE              "None"
INDIVIDUAL        "Individual"
GLOBAL            "Global"
SPECIFIED_DIRECTORY_NOT_CREATED_CLOSE "The specified directory couldn't be created|#27;Close"
CREATE_DIRECTORY  "Create directory"
CREATE_SUBDATAFILE "Create sub data file"
CREATE_DATAFILE   "Create new data file"
MAKE_DATAFILE     "Allegro datafile"
LABEL_OK          " OK "
LABEL_CANCEL      "#27;~Cancel"
NEW_PWD_REMOVE_PREV_YES_NO "The data file has now been store with the new password._Shall the previous password be forgotten?|Yes| No "
NO_PWD_REMOVE_PREV_YES_NO "The data file has now been store without password._Shall the previous password be forgotten?|Yes| No "
NEW_PWD_ADD_REPLACE        "The data file has now been store with the new password._Shall the previous password be forgotten or shall both be kept in memory?|Keep_both|Foreget_it"
SAVE_PASSWORD     "Save password local"
DATAFILE_PROPERTIES "Data file properties"
PASSWORD          "Password"
CLEAN_PREV_PWD    "Clean pwd list"
UPDATE_OBJECTS    "Update objects"
SCALED_IMAGE      "(scaled)"
VIEW_IMAGE        "Viev full size"
DATAFILE_OBJECT   "Data file object"
PROPERTY_LIST     "Property list"
NEW_PROPERTY      "New property"
HEADER_FILES      "Header file generation"
HEADER_FILE_NAME  "File name:"
BROWSE            "Browse..."
MACRO_PREFIX      "Macro prefix (optional):"
DO_GENERATE       "Do generate"
FAILED_IN_HEADER_GENERATION_CLOSE "The generation did fail.|Close"
USE_PALETTE       "Use palette"
UNIMPLEMENTED_VIEWER "Unimplemented viewer"
SELECT_HEADER_FILE "Select header file name"
SELECT             "Select"

<language = pl>
[filedial]
PERMISSIONS_SET_ERROR "Nie mozesz zmienic uprawnien| OK "
MODE_MASK         "Flagi: "
PERMISSIONS       "Uprawnienia"
<start=USER_CAT>
 _ "Wlasciciel:"
 _ "Grupa:"
 _ "Inne:"
<end=NR_USER_CAT>

<start=ACCESS_TYPE>
 _ "Odczyt"
 _ "Zapis"
 _ "Wykonywanie"
<end=NR_ACCESS_TYPE>
EDIT_DISK_OBJECT  "Edytuj obiekt"
LOCATION          "Lokacja:"
NAME              "Nazwa:"
FILE_ACTION       "Akcja"
SIZE              "Rozmiar:"
DATE              "Ostatnia modyfikacja:"
UNKNOWN           "Nieznane"
DAT_SOURCE        "Nazwa zrodla:"
FILETYPE          "Typ pliku:"
ALLEGRO_SUBDIR    "Allegro datafile (katalog)"
ALLEGRO_SOUND     "Allegro sample dzwieku"
ALLEGRO_MIDI      "Allegro midi"
ALLEGRO_MIDI_PAT  "Allegro midi instrument"
ALLEGRO_ANIMATION "Allegro animacja"
ALLEGRO_BITMAP    "Allegro obraz"
ALLEGRO_RLE       "Allegro sprite"
ALLEGRO_CMP       "Allegro skompilowany sprite"
ALLEGRO_CMPX      "Allegro skompilowany mode-x sprite"
ALLEGRO_PAL       "Allegro paleta"
ALLEGRO_FONT      "Allegro font"
ALLEGRO_BINARY    "Allegro plik binarny"
ALLEGRO_USER      "Allegro zdef. przez uzytkownika"
ALLEGRO_DAT       "Allegro datafile"
DIRECTORY_TEXT    "Folder"
FILE_TEXT         "Plik"
IMAGE             "Obraz"
ATTRIBUTE         "Atrybuty"
READ_ONLY         "~R (Tylko do odczytu)"
HIDDEN            "~H (Ukryty)"
SYSTEM            "~S (Systemowy)"
ARCHIVE           "~A (Archiwalny)"
ATTRIB_ERROR_CLOSE_NN "Blad zmiany atrybutu. informacja od systemu:\"%s\"|Zamknij"
ATTRIB_ERROR_UNKNOWN_CLOSE "Blad zmiany atrybutu z nieznanego powodu.|Zamknij"
PACKED            "Pakowanie:"
NONE              "Brak"
INDIVIDUAL        "Indywidualne"
GLOBAL            "Globalne"
SPECIFIED_DIRECTORY_NOT_CREATED_CLOSE "KAtalog nie mozna zostac utworzony|#27;Zamknij"
CREATE_DIRECTORY  "Stworz katalog"
CREATE_SUBDATAFILE "Stworz pod-datafile"
CREATE_DATAFILE   "Stworz nowy data file"
MAKE_DATAFILE     "Allegro datafile"
LABEL_OK          " OK "
LABEL_CANCEL      "#27;~Anuluj"
NEW_PWD_REMOVE_PREV_YES_NO "Data file zostal zapisany z nowym haslem._Czy stare powinno zostac usuniete?|Tak| Nie "
NO_PWD_REMOVE_PREV_YES_NO "Data file zostal zapisany bez hasla._Czy stare powinno zostac usuniete?|Tak| Nie "
NEW_PWD_ADD_REPLACE        "Data file zostal zapisany z nowym haslem._Usunac stare czy zatrzymac obydwa? |Zatrzymaj_obywda|Usun_stare"
SAVE_PASSWORD     "Zapisz haslo"
DATAFILE_PROPERTIES "Wlasciwosci data file"
PASSWORD          "Haslo"
CLEAN_PREV_PWD    "Usun liste hasel"
UPDATE_OBJECTS    "Aktualizuj obiekty"
SCALED_IMAGE      "(skalowane)"
VIEW_IMAGE        "Pokaz pelny rozmiar"
DATAFILE_OBJECT   "obiekt data file"
PROPERTY_LIST     "Lista wlasciwosci"
NEW_PROPERTY      "New property"
HEADER_FILES      "tworzenie naglowka .h"
HEADER_FILE_NAME  "nazwa pliku:"
BROWSE            "przegladaj..."
MACRO_PREFIX      "prefiks (opcja):"
DO_GENERATE       "Wykonaj"
FAILED_IN_HEADER_GENERATION_CLOSE "Blad genereacji naglowka.|Zamknij"
USE_PALETTE       "Use this_palette"
UNIMPLEMENTED_VIEWER "Niezaimplementowana przegladarka"
SELECT_HEADER_FILE "Wybierz nazwe naglowka"
SELECT             "Wybierz"

<language = hu>
[filedial]
PERMISSIONS_SET_ERROR "Önnek nincs engedélye a jogosultságok változtatására| OK "
MODE_MASK         "Jelzõk: "
PERMISSIONS       "Jogosultságok "
<start=USER_CAT>
 _ "Tulajdonos:"
 _ "Csoport:"
 _ "Más:"
<end=NR_USER_CAT>
<start=ACCESS_TYPE>
 _ "Olvas"
 _ "Ír"
 _ "Futtet"
<end=NR_ACCESS_TYPE>
EDIT_DISK_OBJECT  "Lemez objektum szerkesztése"
LOCATION          "Hely:"
NAME              "Név:"
FILE_ACTION       "Mûvelet"
SIZE              "Méret:"
DATE              "Utoljára változtatva:"
UNKNOWN           "Ismeretlen"
DAT_SOURCE        "Forrás-név:"
FILETYPE          "Fájltípus:"
ALLEGRO_SUBDIR    "Allegro datafájl (könyvtár)"
ALLEGRO_SOUND     "Allegro hangminta"
ALLEGRO_MIDI      "Allegro midi fájl"
ALLEGRO_MIDI_PAT  "Allegro midi fájl"
ALLEGRO_ANIMATION "Allegro animáció"
ALLEGRO_BITMAP    "Allegro kép"
ALLEGRO_RLE       "Allegro sprite"
ALLEGRO_CMP       "Allegro lefordított sprite"
ALLEGRO_CMPX      "Allegro mode-x lefordított sprite"
ALLEGRO_PAL       "Allegro paletta"
ALLEGRO_FONT      "Allegro betûtípus"
ALLEGRO_BINARY    "Allegro bináris fájl"
ALLEGRO_USER     "Allegro felhasználói"
ALLEGRO_DAT   "Allegro datafájl"
DIRECTORY_TEXT    "Könyvtár"
FILE_TEXT         "Fájl"
IMAGE             "Kép"
ATTRIBUTE         "Tulajdonságok"
READ_ONLY         "~R (Írásvédett)"
HIDDEN            "~H (Rejtett)"
SYSTEM            "~S (Rendszer fájl)"
ARCHIVE           "~A (Archív fájl)"
ATTRIB_ERROR_CLOSE_NN "A tulajdonság megváltoztatása nem sikerült. Rendszerüzenet:\"%s\"|Bezár"
ATTRIB_ERROR_UNKNOWN_CLOSE "A tulajdonság megváltoztatása ismeretlen okból nem sikerült.|Bezár"
PACKED             "Tömörítés:"
NONE              "Semmi"
INDIVIDUAL        "Egyedi"
GLOBAL            "Globális"
SPECIFIED_DIRECTORY_NOT_CREATED_CLOSE "A megadott könyvtárt nem sikerült léátrehozni|#27;Bezár"
CREATE_DIRECTORY  "Könyvtár létrehozás"
CREATE_SUBDATAFILE "Al adat fájl létrehozás"
CREATE_DATAFILE   "Új adatfájl létrehozás"
MAKE_DATAFILE     "Allegro datafájl"
LABEL_OK          " OK "
LABEL_CANCEL      "#27;~Mégsem"
NEW_PWD_REMOVE_PREV_YES_NO "Az adatfájl eltárolva az új jelszóval._Az elõzõ jelszót elfelejtsem?|Igen| Nem "
NO_PWD_REMOVE_PREV_YES_NO "Az adatfájl eltárolva jelszó nélkül._Az elõzõ jelszót elfelejtsem?|Igen| Nem "
NEW_PWD_ADD_REPLACE        "Az adatfájl eltárolva az új jelszóval._Az elõzõ jelszót elfelejtsem, vagy legyen mindkettõ a memóriában?|Mindkettõ|Elfelejt"
SAVE_PASSWORD     "Jelszó helyi mentése"
DATAFILE_PROPERTIES "Adat fájl tulajdonságok"
PASSWORD          "Jelszó"
CLEAN_PREV_PWD    "Jelszó lista törlése"
UPDATE_OBJECTS    "Objeltumok frissítése"
SCALED_IMAGE      "(méretezett)"
VIEW_IMAGE        "Teljes méret"
DATAFILE_OBJECT   "Adatfájl objektum"
PROPERTY_LIST     "Tulajdonság lista"
NEW_PROPERTY      "Új tulajdonság"
HEADER_FILES      "Fejléc fájl generálás"
HEADER_FILE_NAME  "Fájl név:"
BROWSE            "Tallóz..."
MACRO_PREFIX      "Macro prefix (esetleges):"
DO_GENERATE       "Generál"
FAILED_IN_HEADER_GENERATION_CLOSE "A generálás nem sikerült.|Bezár"
USE_PALETTE       "Paletta alkalmazása"
UNIMPLEMENTED_VIEWER "Nincs megfelelõ nézõ"
SELECT_HEADER_FILE "fejléc fájl kiválasztása"
SELECT             "Kiválaszt"

<language = es>
[filedial]
PERMISSIONS_SET_ERROR "No se te permite cambiar los permisos| Aceptar "
MODE_MASK         "Flags: "
PERMISSIONS       "Permisos "
<start=USER_CAT>
 _ "Dueño:"
 _ "Grupo:"
 _ "Otro:"
<end=NR_USER_CAT>
<start=ACCESS_TYPE>
 _ "Lectura"
 _ "Escritura"
 _ "Ejecución"
<end=NR_ACCESS_TYPE>
EDIT_DISK_OBJECT  "Editar objeto de disco"
LOCATION          "Dirección:"
NAME              "Nombre:"
FILE_ACTION       "Acción"
SIZE              "Tamaño:"
DATE              "Última modificación:"
UNKNOWN           "Desconocido"
DAT_SOURCE        "Nombre origen:"
FILETYPE          "Tipo de archivo:"
ALLEGRO_SUBDIR    "Archivo de datos de Allegro (directorio)"
ALLEGRO_SOUND     "Muestra de sonido de Allegro"
ALLEGRO_MIDI      "Archivo midi de Allegro"
ALLEGRO_MIDI_PAT  "Archivo midi de Allegro"
ALLEGRO_ANIMATION "Animación de Allegro"
ALLEGRO_BITMAP    "Imagen de Allegro"
ALLEGRO_RLE       "Sprite de Allegro"
ALLEGRO_CMP       "Sprite compilado de Allegro"
ALLEGRO_CMPX      "Sprite compilado modo-x de Allegro"
ALLEGRO_PAL       "Paleta de Allegro"
ALLEGRO_FONT      "Fuente de Allegro"
ALLEGRO_BINARY    "Archivo binario de Allegro"
ALLEGRO_USER     "Definido por el usuario de Allegro"
ALLEGRO_DAT   "Archivo de datos de Allegro"
DIRECTORY_TEXT    "Directorio"
FILE_TEXT         "Archivo"
IMAGE             "Imagen"
ATTRIBUTE         "Atributos"
READ_ONLY         "~R (Protegido contra escritura)"
HIDDEN            "~H (Oculto)"
SYSTEM            "~S (Sistema)"
ARCHIVE           "~A (Archivo)"
ATTRIB_ERROR_CLOSE_NN "El comando para cambiar los atrbutos falló. El mensaje del sistema es:\"%s\"|Cerrar"
ATTRIB_ERROR_UNKNOWN_CLOSE "El comando para cambiar los atrbutos falló por razones desconocidas.|Cerrar"
PACKED             "Empaquetado:"
NONE              "Nada"
INDIVIDUAL        "Individual"
GLOBAL            "Global"
SPECIFIED_DIRECTORY_NOT_CREATED_CLOSE "El directorio especificado no se ha podido crear|#27;Cerrar"
CREATE_DIRECTORY  "Crear directorio"
CREATE_SUBDATAFILE "Crear sub-archivo de datos"
CREATE_DATAFILE   "Crear nuevo archivo de datos"
MAKE_DATAFILE     "Archivo de datos de Allegro"
LABEL_OK          " Aceptar "
LABEL_CANCEL      "#27;~Cancelar"
NEW_PWD_REMOVE_PREV_YES_NO "El archivo de datos se ha guardado con el nuevo password._¿Debe olvidarse el password anterior?|Sí| No "
NO_PWD_REMOVE_PREV_YES_NO "El archivo de datos se ha guardado sin password._¿Debe olvidarse el password anterior?|Sí| No "
NEW_PWD_ADD_REPLACE        "El archivo de datos se ha guardado con el nuevo password._Debe olvidarse el password anterior o deben dejarse en memoria ambos?|Mantener ambos|Olvidarlo"
SAVE_PASSWORD     "Salvar password local"
DATAFILE_PROPERTIES "Propiedades del archivo de datos"
PASSWORD          "Password"
CLEAN_PREV_PWD    "Limpiar lista de pwds"
UPDATE_OBJECTS    "Actializar objectos"
SCALED_IMAGE      "(escalada)"
VIEW_IMAGE        "Mostrar tamaño completo"
DATAFILE_OBJECT   "Objeto de archivo de datos"
PROPERTY_LIST     "Lista de propiedades"
NEW_PROPERTY      "Nueva propiedad"
HEADER_FILES      "Generación del archivo de cabecera"
HEADER_FILE_NAME  "Nombre del archivo:"
BROWSE            "Examinar..."
MACRO_PREFIX      "Prefijo de la macro (opcional):"
DO_GENERATE       "Generar"
FAILED_IN_HEADER_GENERATION_CLOSE "La generación de la cabecera falló.|Cerrar"
USE_PALETTE       "Usar paleta"
UNIMPLEMENTED_VIEWER "Visor no implementado"
SELECT_HEADER_FILE "Selecciona el nombre del archivo de cabecera"
SELECT             "Seleccionar"

<language = fr>
[filedial]
PERMISSIONS_SET_ERROR "Vous n'êtes pas autorisé à modifier les droits| Accepter "
MODE_MASK         "Flags: "
PERMISSIONS       "Droits "
<start=USER_CAT>
 _ "Propriétaire:"
 _ "Groupe:"
 _ "Autre:"
<end=NR_USER_CAT>
<start=ACCESS_TYPE>
 _ "Lecture"
 _ "Ecriture"
 _ "Execution"
<end=NR_ACCESS_TYPE>
EDIT_DISK_OBJECT  "Editer objet de disque"
LOCATION          "Adresse:"
NAME              "Nom:"
FILE_ACTION       "Action"
SIZE              "Taille:"
DATE              "Dernière modification:"
UNKNOWN           "Inconnu"
DAT_SOURCE        "Nom de source:"
FILETYPE          "Type d'archive:"
ALLEGRO_SUBDIR    "Fichier de données d'Allegro (repértoire)"
ALLEGRO_SOUND     "Extrait de son d'Allegro"
ALLEGRO_MIDI      "Fichier midi d'Allegro"
ALLEGRO_MIDI_PAT  "Fichier midi d'Allegro"
ALLEGRO_ANIMATION "Animation d'Allegro"
ALLEGRO_BITMAP    "Image d'Allegro"
ALLEGRO_RLE       "Sprite d'Allegro"
ALLEGRO_CMP       "Sprite compilé d'Allegro"
ALLEGRO_CMPX      "Sprite compilé mode-x d'Allegro"
ALLEGRO_PAL       "Palette d'Allegro"
ALLEGRO_FONT      "Police d'Allegro"
ALLEGRO_BINARY    "Fichier binaire d'Allegro"
ALLEGRO_USER      "Défini par l'utilisateur d'Allegro"
ALLEGRO_DAT       "Fichier de données d'Allegro"
DIRECTORY_TEXT    "Répertoire"
FILE_TEXT         "Fichier"
IMAGE             "Image"
ATTRIBUTE         "Attributs"
READ_ONLY         "~R (Protegé contre écriture)"
HIDDEN            "~H (Caché)"
SYSTEM            "~S (Système)"
ARCHIVE           "~A (Archive)"
ATTRIB_ERROR_CLOSE_NN "La commande pour modifier les attributs a échoué. Le message du système est:\"%s\"|Fermer"
ATTRIB_ERROR_UNKNOWN_CLOSE "La commande pour modifier les attributs a échoué pour des raisons inconnues.|Fermer"
PACKED            "Packé:"
NONE              "Rien"
INDIVIDUAL        "Individuel"
GLOBAL            "Global"
SPECIFIED_DIRECTORY_NOT_CREATED_CLOSE "Le répertoire spécifié n'a pas pu être creé|#27;Fermer"
CREATE_DIRECTORY  "Creer répertoire"
CREATE_SUBDATAFILE "Creer sous-fichier de données"
CREATE_DATAFILE   "Creer nouveau fichier de données"
MAKE_DATAFILE     "Fichier de données d'Allegro"
LABEL_OK          " Accepter "
LABEL_CANCEL      "#27;~Annuler"
NEW_PWD_REMOVE_PREV_YES_NO "Le fichier de données a été sauvegardé avec le nouveau mot de passe._Le mot de passe précedant doit-il être oublié?|Oui| Non "
NO_PWD_REMOVE_PREV_YES_NO "Le fichier de données a été sauvegardé sans mot de passe._Le mot de passe précedant doit-il être oublié?|Oui| Non "
NEW_PWD_ADD_REPLACE        "Le fichier de données a été sauvegardé avec le nouveau mot de passe._¿Le mot de passe précedant doit-il être oublié ou sauvegardé avec le nouveau?|Garder les deux|L'oublier"
SAVE_PASSWORD     "Sauvegarder le mot de passe local"
DATAFILE_PROPERTIES "Propiétés du fichier de données"
PASSWORD          "Mot de passe"
CLEAN_PREV_PWD    "Vider liste de mots de passe"
UPDATE_OBJECTS    "Actualiser objets"
SCALED_IMAGE      "(à l'échelle)"
VIEW_IMAGE        "Montrer taille réelle"
DATAFILE_OBJECT   "Objet de fichier de données"
PROPERTY_LIST     "Liste de propiétés"
NEW_PROPERTY      "Nouvelle propiété"
HEADER_FILES      "Generation du fichier d'entête"
HEADER_FILE_NAME  "Nom du fichier:"
BROWSE            "Examiner..."
MACRO_PREFIX      "Prefixe de la macro (optionnel):"
DO_GENERATE       "Générer"
FAILED_IN_HEADER_GENERATION_CLOSE "La génération de l'entête a echoué.|Fermer"
USE_PALETTE       "Utiliser palette"
UNIMPLEMENTED_VIEWER "Viseur non implémenté"
SELECT_HEADER_FILE "Selectionne le nom du fichier d'entête"
SELECT             "Selectionner"

<language = pt>
[filedial]
PERMISSIONS_SET_ERROR "Você não possui permissão para mudar as permissões| Aceitar"
MODE_MASK         "Flags: "
PERMISSIONS       "Permissões "
<start=USER_CAT>
 _ "Proprietário:"
 _ "Grupo:"
 _ "Outro:"
<end=NR_USER_CAT>
<start=ACCESS_TYPE>
 _ "Ler"
 _ "Escrever"
 _ "Executar"
<end=NR_ACCESS_TYPE>
EDIT_DISK_OBJECT  "Editar objeto de disco"
LOCATION          "Localização:"
NAME              "Nome:"
FILE_ACTION       "Ação"
SIZE              "Tamanho:"
DATE              "Última mudança em:"
UNKNOWN           "Desconhecido"
DAT_SOURCE        "Nome de Origem:"
FILETYPE          "Tipo de arquivo:"
ALLEGRO_SUBDIR    "Arquivo de dados do Allegro (diretório)"
ALLEGRO_SOUND     "Amostra de som do Allegro"
ALLEGRO_MIDI      "Arquivo midi do Allegro"
ALLEGRO_MIDI_PAT  "Arquivo midi do Allegro"
ALLEGRO_ANIMATION "Animação do Allegro"
ALLEGRO_BITMAP    "Imagem do Allegro"
ALLEGRO_RLE       "Sprite do Allegro"
ALLEGRO_CMP       "Aprite compilado do Allegro"
ALLEGRO_CMPX      "Sprite compilado modo-x do Allegro"
ALLEGRO_PAL       "Paleta do Allegro"
ALLEGRO_FONT      "Fonte do Allegro"
ALLEGRO_BINARY    "Arquivo binário do Allegro"
ALLEGRO_USER     "Definido por um usuário do Allegro"
ALLEGRO_DAT   "Arquivo de dados do Allegro"
DIRECTORY_TEXT    "Diretório"
FILE_TEXT         "Arquivo"
IMAGE             "Imagem"
ATTRIBUTE         "Atributos"
READ_ONLY         "~R (Protegido contra escrita)"
HIDDEN            "~H (Oculto)"
SYSTEM            "~S (Arquivos de sistema)"
ARCHIVE           "~A (Arquivo)"
ATTRIB_ERROR_CLOSE_NN "O comando para mudar o atributo falhou. A mensagem do sistema é:\"%s\"|Fechar"
ATTRIB_ERROR_UNKNOWN_CLOSE "O comando para mudar o atributo falhou por razões desconhecidas.|Fechar"
PACKED             "Empacotado:"
NONE              "Nada"
INDIVIDUAL        "Individual"
GLOBAL            "Global"
SPECIFIED_DIRECTORY_NOT_CREATED_CLOSE "Não se poude criar o diretório especificado|#27;Fechar"
CREATE_DIRECTORY  "Criar diretório"
CREATE_SUBDATAFILE "Criar sub-arquivo de dados"
CREATE_DATAFILE   "Criar novo arquivo de dados"
MAKE_DATAFILE     "Arquivo de dados do Allegro"
LABEL_OK          " Aceitar "
LABEL_CANCEL      "#27;~Cancelar"
NEW_PWD_REMOVE_PREV_YES_NO "O arquivo de dados foi armazenado com a nova senha. Deseja desfazer-se da senha anterior|Sim| Não"
NO_PWD_REMOVE_PREV_YES_NO "O arquivo de dados foi armazenado sem senha. Deseja desfazer-se da senha anterior|Sim| Não"
NEW_PWD_ADD_REPLACE        "O arquivo de dados foi armazenado com a nova senha. Deseja desfazer-se da senha anterior ou deseja manter ambos em memória?|Manter ambos|Desfazer-se dela"
SAVE_PASSWORD     "Salvar senha local"
DATAFILE_PROPERTIES "Propriedades do arquivo de dados"
PASSWORD          "Senha"
CLEAN_PREV_PWD    "Limpar lista de Pwds"
UPDATE_OBJECTS    "Atualizar objetos"
SCALED_IMAGE      "(escalada)"
VIEW_IMAGE        "Visualizar todo o tamanho"
DATAFILE_OBJECT   "Objeto do arquivo de dados"
PROPERTY_LIST     "Lista de propriedades"
NEW_PROPERTY      "Nova propriedade"
HEADER_FILES      "Geração do arquivo de cabeçalho"
HEADER_FILE_NAME  "Nome do arquivo:"
BROWSE            "Navegador..."
MACRO_PREFIX      "Prefixo da macro (opcional)"
DO_GENERATE       "Gerar"
FAILED_IN_HEADER_GENERATION_CLOSE "A geração falhou.|Fechar"
USE_PALETTE       "Usar paleta"
UNIMPLEMENTED_VIEWER "Visualizador não implementado"
SELECT_HEADER_FILE "Selecione o nome do arquivo de cabeçalho"
SELECT             "Selecionar"
