<language=en>
[formatletters]
LETTER_DAY	"D"
LETTER_MONTH	"M"
LETTER_YEAR	"Y"
LETTER_HOUR	"h"
LETTER_MINUTE	"m"
LETTER_SECOND	"s"
[shortmonths]
JAN		"Jan"
FEB		"Feb"
MAR		"Mar"
APR		"Apr"
MAY		"May"
JUN		"Jun"
JUL		"Jul"
AUG		"Aug"
SEP		"Sep"
OCT		"Oct"
NOV		"Nov"
DEC		"Dec"
[longmonths]
JANUARY		"January"
FEBRUARY	"February"
MARCH		"March"
APRIL		"April"
MAY		"May"
JUNE		"June"
JULY		"July"
AUGUST		"August"
SEPTEMBER	"September"
OCTOBER		"October"
NOVEMBER	"November"
DECEMBER	"December"
[shortdays]
SUN		"Sun"
MON		"Mon"
TUE		"Tue"
WED		"Wed"
THU		"Thu"
FRI		"Fri"
SAT		"Sat"
[longdays]
SUNDAY		"Sunday"
MONDAY		"Monday"
TUESDAY		"Tuesday"
WEDNESDAY	"Wednesday"
THURSDAY	"Thursday"
FRIDAY		"Friday"
SATURDAY	"Saturday"

<language=pl>
[formatletters]
LETTER_DAY	"D"
LETTER_MONTH	"M"
LETTER_YEAR	"Y"
LETTER_HOUR	"h"
LETTER_MINUTE	"m"
LETTER_SECOND	"s"
[shortmonths]
JAN		"Jan"
FEB		"Feb"
MAR		"Mar"
APR		"Apr"
MAY		"May"
JUN		"Jun"
JUL		"Jul"
AUG		"Aug"
SEP		"Sep"
OCT		"Oct"
NOV		"Nov"
DEC		"Dec"
[longmonths]
JANUARY		"January"
FEBRUARY	"February"
MARCH		"March"
APRIL		"April"
MAY		"May"
JUNE		"June"
JULY		"July"
AUGUST		"August"
SEPTEMBER	"September"
OCTOBER		"October"
NOVEMBER	"November"
DECEMBER	"December"
[shortdays]
SUN		"Sun"
MON		"Mon"
TUE		"Tue"
WED		"Wed"
THU		"Thu"
FRI		"Fri"
SAT		"Sat"
[longdays]
SUNDAY		"Sunday"
MONDAY		"Monday"
TUESDAY		"Tuesday"
WEDNESDAY	"Wednesday"
THURSDAY	"Thursday"
FRIDAY		"Friday"
SATURDAY	"Saturday"

<language=hu>
[formatletters]
LETTER_DAY	"D"
LETTER_MONTH	"M"
LETTER_YEAR	"Y"
LETTER_HOUR	"h"
LETTER_MINUTE	"m"
LETTER_SECOND	"s"
[shortmonths]
JAN		"Jan"
FEB		"Feb"
MAR		"Mar"
APR		"Apr"
MAY		"May"
JUN		"Jun"
JUL		"Jul"
AUG		"Aug"
SEP		"Sep"
OCT		"Oct"
NOV		"Nov"
DEC		"Dec"
[longmonths]
JANUARY		"January"
FEBRUARY	"February"
MARCH		"March"
APRIL		"April"
MAY		"May"
JUNE		"June"
JULY		"July"
AUGUST		"August"
SEPTEMBER	"September"
OCTOBER		"October"
NOVEMBER	"November"
DECEMBER	"December"
[shortdays]
SUN		"Sun"
MON		"Mon"
TUE		"Tue"
WED		"Wed"
THU		"Thu"
FRI		"Fri"
SAT		"Sat"
[longdays]
SUNDAY		"Sunday"
MONDAY		"Monday"
TUESDAY		"Tuesday"
WEDNESDAY	"Wednesday"
THURSDAY	"Thursday"
FRIDAY		"Friday"
SATURDAY	"Saturday"

<language=es>
[formatletters]
LETTER_DAY	"D"
LETTER_MONTH	"M"
LETTER_YEAR	"Y"
LETTER_HOUR	"h"
LETTER_MINUTE	"m"
LETTER_SECOND	"s"
[shortmonths]
JAN		"Jan"
FEB		"Feb"
MAR		"Mar"
APR		"Apr"
MAY		"May"
JUN		"Jun"
JUL		"Jul"
AUG		"Aug"
SEP		"Sep"
OCT		"Oct"
NOV		"Nov"
DEC		"Dec"
[longmonths]
JANUARY		"January"
FEBRUARY	"February"
MARCH		"March"
APRIL		"April"
MAY		"May"
JUNE		"June"
JULY		"July"
AUGUST		"August"
SEPTEMBER	"September"
OCTOBER		"October"
NOVEMBER	"November"
DECEMBER	"December"
[shortdays]
SUN		"Sun"
MON		"Mon"
TUE		"Tue"
WED		"Wed"
THU		"Thu"
FRI		"Fri"
SAT		"Sat"
[longdays]
SUNDAY		"Sunday"
MONDAY		"Monday"
TUESDAY		"Tuesday"
WEDNESDAY	"Wednesday"
THURSDAY	"Thursday"
FRIDAY		"Friday"
SATURDAY	"Saturday"

<language=fr>
[formatletters]
LETTER_DAY	"D"
LETTER_MONTH	"M"
LETTER_YEAR	"Y"
LETTER_HOUR	"h"
LETTER_MINUTE	"m"
LETTER_SECOND	"s"
[shortmonths]
JAN		"Jan"
FEB		"Feb"
MAR		"Mar"
APR		"Apr"
MAY		"May"
JUN		"Jun"
JUL		"Jul"
AUG		"Aug"
SEP		"Sep"
OCT		"Oct"
NOV		"Nov"
DEC		"Dec"
[longmonths]
JANUARY		"January"
FEBRUARY	"February"
MARCH		"March"
APRIL		"April"
MAY		"May"
JUNE		"June"
JULY		"July"
AUGUST		"August"
SEPTEMBER	"September"
OCTOBER		"October"
NOVEMBER	"November"
DECEMBER	"December"
[shortdays]
SUN		"Sun"
MON		"Mon"
TUE		"Tue"
WED		"Wed"
THU		"Thu"
FRI		"Fri"
SAT		"Sat"
[longdays]
SUNDAY		"Sunday"
MONDAY		"Monday"
TUESDAY		"Tuesday"
WEDNESDAY	"Wednesday"
THURSDAY	"Thursday"
FRIDAY		"Friday"
SATURDAY	"Saturday"

<language=se>
[formatletters]
LETTER_DAY	"D"
LETTER_MONTH	"M"
LETTER_YEAR	"Å"
LETTER_HOUR	"h"
LETTER_MINUTE	"m"
LETTER_SECOND	"s"
[shortmonths]
JAN		"jan"
FEB		"feb"
MAR		"mar"
APR		"apr"
MAY		"maj"
JUN		"jun"
JUL		"jul"
AUG		"aug"
SEP		"sep"
OCT		"okt"
NOV		"nov"
DEC		"dec"
[longmonths]
JANUARY		"januari"
FEBRUARY	"februari"
MARCH		"mars"
APRIL		"april"
MAY		"maj"
JUNE		"juni"
JULY		"juli"
AUGUST		"augusti"
SEPTEMBER	"september"
OCTOBER		"oktober"
NOVEMBER	"november"
DECEMBER	"december"
[shortdays]
SUN		"sön"
MON		"mån"
TUE		"tis"
WED		"ons"
THU		"tor"
FRI		"fre"
SAT		"lör"
[longdays]
SUNDAY		"söndag"
MONDAY		"måndag"
TUESDAY		"tisdat"
WEDNESDAY	"onsdag"
THURSDAY	"torsdag"
FRIDAY		"fredag"
SATURDAY	"lördag"

<language=pt>
[formatletters]
LETTER_DAY	"D"
LETTER_MONTH	"M"
LETTER_YEAR	"A"
LETTER_HOUR	"h"
LETTER_MINUTE	"m"
LETTER_SECOND	"s"
[shortmonths]
JAN		"Jan"
FEB		"Fev"
MAR		"Mar"
APR		"Abr"
MAY		"Mai"
JUN		"Jun"
JUL		"Jul"
AUG		"Ago"
SEP		"Set"
OCT		"Out"
NOV		"Nov"
DEC		"Dez"
[longmonths]
JANUARY		"Janeiro"
FEBRUARY	"Fevereiro"
MARCH		"Março"
APRIL		"Abril"
MAY		"Maio"
JUNE		"Junho"
JULY		"Julho"
AUGUST		"Agosto"
SEPTEMBER	"Setembro"
OCTOBER		"Outubro"
NOVEMBER	"Novembro"
DECEMBER	"Dezembro"
[shortdays]
SUN		"Dom"
MON		"seg"
TUE		"Ter"
WED		"Qua"
THU		"Qui"
FRI		"Sex"
SAT		"Sáb"
[longdays]
SUNDAY		"Domingo"
MONDAY		"Segunda"
TUESDAY		"Terça"
WEDNESDAY	"Quarta"
THURSDAY	"Quinta"
FRIDAY		"Sexta"
SATURDAY	"Sábado"
