/* src/labldata.c
 * 
 *  Source for data encoded from resource/cgui.dat .
 *  Do not hand edit.
 */

#include <allegro.h>
#include <allegro/internal/aintern.h>



static DATAFILE_PROPERTY cgui_cguilabl_prop[] = {
    { "1-30-2017, 20:17", DAT_ID('D', 'A', 'T', 'E') },
    { "CGUILABL", DAT_ID('N', 'A', 'M', 'E') },
    { "/home/christer/prog/base_cgui/cgui-base/resource/c"
      "guilabl", DAT_ID('O', 'R', 'I', 'G') },
    { 0, DAT_END }
};

const unsigned char cgui_cguilabl[32545] = 
    "<en>\n[clock\n\"Adjust watch settings\n\"Apply\n\"Show se"
    "conds\n\"#27;Close\n[file_import_query\n\"Properties of"
    " imported object\n\"Name:\n\"Type:\n\"Matching_types\n\"Al"
    "l_types\n\"Do import\n\"Skip import\n\"You must check at"
    " least one type.| OK \n\"Fonts can only use 8 bits c"
    "olour depth.| OK \n\"Enter password:\n\"#10; ~OK \n\"#27"
    ";~Cancel\n\"The entered password is incorrect. Try a"
    "gain| OK \n\"Clean pwd list\n\"Save local\n\"Shall the e"
    "xisting object (%s) be updated or a new created?|U"
    "pdate|New\n\"Prettify name\n\"Use relative path\n[fileb"
    "row\n\"Disk device:\n\"Show:\n\"#27;~Cancel\n\"Illegal fil"
    "e|~OK\n\"Selected:\n\"Create sub directory\n\"Create All"
    "egro data file\n\"#settings;Settings\n\"Are you sure t"
    "hat you want to remove the directory \"%s\" (all tha"
    "t may be stored in it will be deleted)?|Yes| No \n\""
    "Are you sure that you want to remove the file \"%s\""
    ".|Yes| No \n\"|Yes_to all\n\"The removing of the disk "
    "object is not fulfilled|Continue\n\"%s is a director"
    "y|Close\n\"%s is no directory|Close\n\"%s does not not"
    " exist. Try again.|Close\n\"%s does already exist, a"
    "re you really sure?|Yes|Cancel\n\"%s does already ex"
    "ist, please try again|OK\n\"Open new file-browser\n\"C"
    "GUI file-selector\n\"CGUI file-manager\n\"OK\n\"Edit pro"
    "perties\n\"Copy file\n\"Cut file\n\"Delete\n\"Paste\n\"Selec"
    "t\n\"Show image\n\"Preview window\n\"Show original place"
    "\n\"Show update time\n\"Show size\n\"Show attributes\n\"Sh"
    "ow permissions\n\"Show hidden/system files\n\"Show cop"
    "y buffer\n\"Formatted names\n\"No name present\n\"Error "
    "message\n\"The directory listing may be incomplete d"
    "ue to and unknown error|OK\n\"dir\n\"dirs\n\"file\n\"files"
    "\n\"MB\n\"kB\n\"bytes\n\"Location:\n\"Action\n\"Enter password"
    "\n\"\n\"Name\n\"Changed\n\"Size(k)\n\"Attrib\n\"\n\"Name\n\"Change"
    "d\n\"Size(k)\n\"Permissions\n[filebuff\n\"Selection buffe"
    "r\n\"#27;Close\n\"Clean\n\"Add mode\n\"The specified file "
    "does already exist, replace it?|Yes|No\n\"Error when"
    " trying to read the file|Close\n\"Error when trying "
    "to create the new file|Close\n\"The directory %s cou"
    "ld not be removed. Message from the system: %s|Clo"
    "se\n\"The file %s could not be removed. Message from"
    " the system: %s|Close\n\"The Allegro datafile object"
    " %s could not be removed. Message from the system:"
    " %s|Close\n[filedial\n\"You are not allowed to change"
    " the permissions| OK \n\"Flags: \n\"Permissions \n\"Edit"
    " disk object\n\"Location:\n\"Name:\n\"Action\n\"Size:\n\"Lat"
    "est change at:\n\"Unknown\n\"Source-name:\n\"Type of fil"
    "e:\n\"Allegro datafile (directory)\n\"Allegro sound sa"
    "mple\n\"Allegro midi file\n\"Allegro midi file\n\"Allegr"
    "o animation\n\"Allegro image\n\"Allegro sprite\n\"Allegr"
    "o compiled sprite\n\"Allegro mode-x compiled sprite\n"
    "\"Allegro palette\n\"Allegro font\n\"Allegro binary fil"
    "e\n\"Allegro user-defined\n\"Allegro datafile\n\"Directo"
    "ry\n\"File\n\"Image\n\"Attributes\n\"~R (Write protected)\n"
    "\"~H (Hidden)\n\"~S (System file)\n\"~A (Archive file)\n"
    "\"The command to change attribute failed. The messa"
    "ge from the system is:\"%s\"|Close\n\"The command to c"
    "hange attribute failed for unknown reasons.|Close\n"
    "\"Packing:\n\"None\n\"Individual\n\"Global\n\"The specified"
    " directory couldn't be created|#27;Close\n\"Create d"
    "irectory\n\"Create sub data file\n\"Create new data fi"
    "le\n\"Allegro datafile\n\" OK \n\"#27;~Cancel\n\"The data "
    "file has now been store with the new password._Sha"
    "ll the previous password be forgotten?|Yes| No \n\"T"
    "he data file has now been store without password._"
    "Shall the previous password be forgotten?|Yes| No "
    "\n\"The data file has now been store with the new pa"
    "ssword._Shall the previous password be forgotten o"
    "r shall both be kept in memory?|Keep_both|Foreget_"
    "it\n\"Save password local\n\"Data file properties\n\"Pas"
    "sword\n\"Clean pwd list\n\"Update objects\n\"(scaled)\n\"V"
    "iev full size\n\"Data file object\n\"Property list\n\"Ne"
    "w property\n\"Header file generation\n\"File name:\n\"Br"
    "owse...\n\"Macro prefix (optional):\n\"Do generate\n\"Th"
    "e generation did fail.|Close\n\"Use palette\n\"Unimple"
    "mented viewer\n\"Select header file name\n\"Select\n\"Ow"
    "ner:\n\"Group:\n\"Other:\n\"Read\n\"Write\n\"Execute\n[format"
    "letters\n\"D\n\"M\n\"Y\n\"h\n\"m\n\"s\n[graphini\n\"Enter new scr"
    "een setting\n\"Settings\n\"Info\n\"Available modes\n\"Curr"
    "ent mode\n\"Selected mode\n\"Set mode\n\"Previously fail"
    "ed with mo de\n\"Graphics driver:\n\"Allegro failed to"
    " detect available screen modes\n\"more tries before\n"
    "\"#27;Close\n[longdays\n\"Sunday\n\"Monday\n\"Tuesday\n\"Wed"
    "nesday\n\"Thursday\n\"Friday\n\"Saturday\n[longmonths\n\"Ja"
    "nuary\n\"February\n\"March\n\"April\n\"May\n\"June\n\"July\n\"Au"
    "gust\n\"September\n\"October\n\"November\n\"December\n[obte"
    "xt\n\"Error opening file %s.|#27;Continue\n[shortdays"
    "\n\"Sun\n\"Mon\n\"Tue\n\"Wed\n\"Thu\n\"Fri\n\"Sat\n[shortmonths\n\""
    "Jan\n\"Feb\n\"Mar\n\"Apr\n\"May\n\"Jun\n\"Jul\n\"Aug\n\"Sep\n\"Oct\n\""
    "Nov\n\"Dec\n<se>\n[clock\n\"Klockans inst\xe4llningar\n\"Verk"
    "st\xe4ll\n\"Visa sekunder\n\"#27;St\xe4ng\n[file_import_query"
    "\n\"Egenskaper f\xf6r importerat objekt\n\"Namn:\n\"Typ:\n\"M"
    "atchande_typer\n\"Alla_typer\n\"Importera\n\"Importera e"
    "j\n\"Du m\xe5ste v\xe4lja n\xe5gon typ.| OK \n\"Fonter kr\xe4ver 8"
    " bitars f\xe4rgdjup.| OK \n\"Ange l\xf6sen:\n\"#10; ~OK \n\"#2"
    "7;~Avbryt\n\"Det angivna l\xf6senordet \xe4r felaktigt. F\xf6"
    "rs\xf6k igen| OK \n\"Radera l\xf6senordslistan\n\"Spara loka"
    "lt\n\"Ska det befintliga objektet (%s) uppdateras el"
    "ler ska ett nytt skapas?|Uppdatera|Skapa nytt\n\"Sny"
    "gga till namn\n\"Anv\xe4nd relativ s\xf6kv\xe4g\n[filebrow\n\"En"
    "het:\n\"Visa:\n\"#27;~Avbryt\n\"Ogiltig fil|~OK\n\"Vald:\n\""
    "Skapa underkatalog\n\"Skapa en Allegro datafil\n\"#set"
    "tings;Anpassa\n\"\xc4r du s\xe4ker p\xe5 att du vill ta bort "
    "katalogen \"%s\" (allt som eventuellt finns i den ko"
    "mmer ocks\xe5 att tas bort)?|Ta bort|Avbryt\n\"\xc4r du s\xe4"
    "ker p\xe5 att du vill ta bort filen \"%s\"|Ta bort|Avbr"
    "yt\n\"|Ja till_alla\n\"Borttagande av filobjektet har "
    "inte fullf\xf6ljts|Forts\xe4tt\n\"%s \xe4r en katalog|St\xe4ng\n\""
    "%s \xe4r inte en katalog|St\xe4ng\n\"%s finns inte. F\xf6rs\xf6k"
    " igen|St\xe4ng\n\"%s finns redan, \xe4r du verkligen s\xe4ker"
    "?|Japp|Avbryt\n\"%s finns redan, f\xf6rs\xf6k igen.|OK\n\"\xd6p"
    "pna ny fil-bl\xe4""ddrare\n\"CGUI:s filv\xe4ljare\n\"CGUI:s fi"
    "l\xf6vervakare\n\"OK\n\"Byt namn\n\"Kopiera fil\n\"Klipp ut f"
    "il\n\"Ta bort\n\"Klistra in\n\"V\xe4lj\n\"Visa bild\n\"F\xf6rhands"
    "granskning\n\"Visa originalplats\n\"Visa \xe4ndringstid\n\""
    "Visa storlek\n\"Visa attribut\n\"Visa r\xe4ttigheter\n\"Vis"
    "a g\xf6mda-/systemfiler\n\"Visa kopieringsbuffert\n\"Form"
    "atterade namn\n\"Namn saknas\n\"Felmeddelande\n\"Den vis"
    "ade filkatalogen kan vara ofullst\xe4ndig pga ok\xe4nt f"
    "el.|St\xe4ng\n\"katalog\n\"kataloger\n\"fil\n\"filer\n\"MB\n\"kB\n"
    "\"bytes\n\"Plats:\n\"K\xf6r\n\"Ange l\xf6sen\n\"\n\"Namn\n\"\xc4ndrad\n\"S"
    "torlek(k)\n\"Attrib\n\"\n\"Namn\n\"\xc4ndrad\n\"Storlek(k)\n\"R\xe4t"
    "tigheter\n[filebuff\n\"M\xe4rkta filer\n\"#27;St\xe4ng\n\"T\xf6m\n\""
    "L\xe4gg till\n\"Den angivna filen finns redan, ska den "
    "ers\xe4ttas|Ja|Nej\n\"Det blev fel filen skulle l\xe4sas|S"
    "t\xe4ng\n\"Det blev fel n\xe4r den nya filen skulle skapas"
    "|St\xe4ng\n\"Det gick inte att ta bort katalogen %s. Me"
    "ddelandet fr\xe5n systemet lyder:\"%s\"|St\xe4ng\n\"Det gick"
    " inte att ta bort filen %s. Meddelandet fr\xe5n syste"
    "met lyder:\"%s\"|St\xe4ng\n\"Det gick inte att ta bort da"
    "tafilsobjektet %s. Meddelandet fr\xe5n systemet lyder"
    ":\"%s\"|St\xe4ng\n[filedial\n\"Det \xe4r inte till\xe5tet f\xf6r di"
    "g att \xe4ndra r\xe4ttigheterna| OK \n\"Flaggor: \n\"R\xe4ttigh"
    "eter\n\"Redigera diskobjekt\n\"Plats:\n\"Namn:\n\"K\xf6r\n\"Sto"
    "rlek:\n\"Senast \xe4ndrad:\n\"Ok\xe4nt\n\"Ursprungsnamn:\n\"Typ "
    "av fil:\n\"Allegro datafil, underkatalog\n\"Allegro lj"
    "udinspelning\n\"Allegro midi fil\n\"Allegro midi fil\n\""
    "Allegro animation\n\"Allegro bild\n\"Allegro sprite\n\"A"
    "llegro kompilerad sprite\n\"Allegro mode-x kompilera"
    "d sprite\n\"Allegro palett\n\"Allegro font\n\"Allegro bi"
    "n\xe4rfil\n\"Allegro till\xe4mpningsspecifikt objekt\n\"Alle"
    "gro datafil\n\"Filkatalog\n\"Fil\n\"Bild\n\"Attribut\n\"~R ("
    "Skrivskyddad)\n\"~H (Dold)\n\"~S (Systemfil)\n\"~A (Arki"
    "vfil)\n\"Kommandot att \xe4ndra p\xe5 attribut misslyckade"
    "s. Meddelandet fr\xe5n systemet lyder:\"%s\"|St\xe4ng\n\"Kom"
    "mandot att \xe4ndra p\xe5 attribut misslyckades av ok\xe4nd"
    " anledning.|St\xe4ng\n\"Packning:\n\"Ingen\n\"Individuell\n\""
    "Global\n\"Den angivna katalogen kan inte skapas|#27;"
    "St\xe4ng\n\"Skapa katalog\n\"Skapa n\xe4stlad datafil\n\"Skapa"
    " ny datafil\n\"Allegro datafil\n\" OK \n\"#27;~Avbryt\n\"D"
    "atafilen har nu sparats med det nya l\xf6senordet._Sk"
    "a det gamla l\xf6senordet gl\xf6mmas?| Ja |Nej\n\"Datafile"
    "n har nu sparats utan l\xf6senordet._Ska det tidigare"
    " l\xf6senordet gl\xf6mmas?| Ja |Nej\n\"Datafilen har nu sp"
    "arats med det nya l\xf6senordet._Ska det tidigare anv"
    "\xe4nda l\xf6senordet gl\xf6mmas eller ska b\xe5""da beh\xe5llas i "
    "minnet?|Beh\xe5ll_b\xe5""da|Gl\xf6m\n\"Spara l\xf6sen lokalt\n\"Data"
    "filsegenskaper\n\"L\xf6senord\n\"Radera l\xf6senordslistan\n\""
    "Uppdatera objekten\n\"(skalad)\n\"Visa full storlek\n\"D"
    "atafilobjekt\n\"Egenskapslista\n\"Ny egenskap\n\"H-fil g"
    "enerering\n\"Fil namn:\n\"Bl\xe4""ddra...\n\"Makro prefix (va"
    "lfri):\n\"Generera filen!\n\"Genereringen misslyckades"
    "|St\xe4ng\n\"Anv\xe4nd paletten\n\"Denna objekttyp saknar vi"
    "sningsfunktion\n\"Ange namn f\xf6r h-filen\n\"V\xe4lj\n\"\xc4gare"
    ":\n\"Grupp:\n\"Andra:\n\"L\xe4sa\n\"Skriva\n\"Exekvera\n[formatl"
    "etters\n\"D\n\"M\n\"\xc5\n\"h\n\"m\n\"s\n[graphini\n\"St\xe4ll in sk\xe4rm"
    "l\xe4ge\n\"Inst\xe4llning\n\"Info\n\"Existerande sk\xe4rml\xe4gen\n\"N"
    "uvarande inst\xe4llning\n\"Valt nytt l\xe4ge\n\"Verkst\xe4ll\n\"T"
    "idigare misslyckats med:\n\"Grafikdrivrutin:\n\"Allegr"
    "o kunde inte avg\xf6ra vilka sk\xe4rml\xe4gen som finns\n\"fl"
    "er f\xf6rs\xf6k innan dess\n\"#27;St\xe4ng\n[longdays\n\"s\xf6ndag\n"
    "\"m\xe5ndag\n\"tisdat\n\"onsdag\n\"torsdag\n\"fredag\n\"l\xf6rdag\n["
    "longmonths\n\"januari\n\"februari\n\"mars\n\"april\n\"maj\n\"j"
    "uni\n\"juli\n\"augusti\n\"september\n\"oktober\n\"november\n\""
    "december\n[obtext\n\"Det g\xe5r inte att \xf6ppna filen %s."
    "|#27;Forts\xe4tt\n[shortdays\n\"s\xf6n\n\"m\xe5n\n\"tis\n\"ons\n\"tor\n"
    "\"fre\n\"l\xf6r\n[shortmonths\n\"jan\n\"feb\n\"mar\n\"apr\n\"maj\n\"j"
    "un\n\"jul\n\"aug\n\"sep\n\"okt\n\"nov\n\"dec\n<pl>\n[clock\n\"Zmie"
    "n ustawienia zegara\n\"Zastosuj\n\"Pokaz sekundy\n\"#27;"
    "Zamknij\n[file_import_query\n\"Wlasciwosci zaimportow"
    "anych obiektow\n\"Nazwa:\n\"Typ:\n\"zgodne_typy\n\"wszystk"
    "ie_typy\n\"Importuj\n\"Pomin import\n\"Sprawdz przynajmn"
    "iej jeden typ.| OK \n\"Fonty moga uzywac tylko 8 bit"
    "owej glebi koloru.| OK \n\"Wprowadz haslo:\n\"#10; ~OK"
    " \n\"#27;~Anuluj\n\"Nieprwaidlowe haslo. sprobuj jeszc"
    "ze raz| OK \n\"Wyczysc liste hasel\n\"Zapisz haslo\n\"Ob"
    "iekt (%s) ma zostac zaktualizowany czy zapisany ja"
    "ko inny?|Aktualizuj|Zapisz jako inny\n\"lepsza nazwa"
    "\n\"Relatywna sciezka\n[filebrow\n\"Naped:\n\"Pokaz:\n\"#27"
    ";~Anuluj\n\"Niepoprawny plik|~OK\n\"Zaznaczone:\n\"Stwor"
    "z folder\n\"Stworz Allegro data file\n\"#settings;Usta"
    "wienia\n\"Czy na pewno usunac folder \"%s\" ? |Tak| Ni"
    "e \n\"Czy na pewno usunac plik \"%s\".|Tak| Nie \n\"|Tak"
    " na wszystkie\n\"Blad usuwania pliku|Kontynuuj\n\"%s j"
    "est folderem|Zamknij\n\"%s NIE jest folderem|Zamknij"
    "\n\"%s nie istnieje. sprobuj ponownie.|Zamknij\n\"%s j"
    "uz istnieje, czy kontynuowac?|Tak|Anuluj\n\"%s juz i"
    "stnieje. sprobuj ponownie.|OK\n\"Otworz nowa przegla"
    "darke\n\"CGUI - wybor pliku\n\"CGUI - manager plikow\n\""
    "OK\n\"Wlasciwosci\n\"Kopiuj\n\"Wytnij\n\"Usun\n\"Wklej\n\"Wybi"
    "erz\n\"Pokaz obraz\n\"Okno podgladu\n\"Pokaz orignalna s"
    "ciezke\n\"Pokaz czas modyfikacji\n\"Pokaz rozmiar\n\"Pok"
    "az atrybuty\n\"Pokaz uprawnienia\n\"Pokaz pliki ukryte"
    "/systemowe\n\"Pokaz bufor kopiowania\n\"przeformatowan"
    "e nazwy\n\"brak nazwy\n\"Informacja o bledzie\n\"Wypis z"
    "awartosci folderu moze byc niekompletny z powodu n"
    "ieznanego bledu|OK\n\"dir\n\"dirs\n\"Plik\n\"Pliki\n\"MB\n\"kB"
    "\n\"bajtow\n\"Lokacja:\n\"Akacja\n\"Wprowadz haslo\n\"\n\"Nazw"
    "y\n\"Zmieniony\n\"Rozmiar(k)\n\"Atryb.\n\"\n\"Nazwy\n\"Zmienio"
    "ny\n\"Rozmiar(k)\n\"Permissions\n[filebuff\n\"Bufor zazna"
    "czenia\n\"#27;Zamknij\n\"Wyczysc\n\"Tryb dodawania\n\"Plik"
    " juz istnieje, nadpisac go?|Tak|Nie\n\"Wystapil blad"
    " podczas czytania pliku|Zamknij\n\"Wystapil blad pod"
    "czas tworzenia pliku|Zamknij\n\"Katalog %s nie moze "
    "zostac usuniety. informacja od systemu: %s|Zamknij"
    "\n\"Plik %s nie moze zostac usuniety. informacja od "
    "systemu: %s|Zamknij\n\"Obiekt %s w datafile nie moze"
    " zostac usuniety. informacja od systemu %s|Zamknij"
    "\n[filedial\n\"Nie mozesz zmienic uprawnien| OK \n\"Fla"
    "gi: \n\"Uprawnienia\n\"Edytuj obiekt\n\"Lokacja:\n\"Nazwa:"
    "\n\"Akcja\n\"Rozmiar:\n\"Ostatnia modyfikacja:\n\"Nieznane"
    "\n\"Nazwa zrodla:\n\"Typ pliku:\n\"Allegro datafile (kat"
    "alog)\n\"Allegro sample dzwieku\n\"Allegro midi\n\"Alleg"
    "ro midi instrument\n\"Allegro animacja\n\"Allegro obra"
    "z\n\"Allegro sprite\n\"Allegro skompilowany sprite\n\"Al"
    "legro skompilowany mode-x sprite\n\"Allegro paleta\n\""
    "Allegro font\n\"Allegro plik binarny\n\"Allegro zdef. "
    "przez uzytkownika\n\"Allegro datafile\n\"Folder\n\"Plik\n"
    "\"Obraz\n\"Atrybuty\n\"~R (Tylko do odczytu)\n\"~H (Ukryt"
    "y)\n\"~S (Systemowy)\n\"~A (Archiwalny)\n\"Blad zmiany a"
    "trybutu. informacja od systemu:\"%s\"|Zamknij\n\"Blad "
    "zmiany atrybutu z nieznanego powodu.|Zamknij\n\"Pako"
    "wanie:\n\"Brak\n\"Indywidualne\n\"Globalne\n\"KAtalog nie "
    "mozna zostac utworzony|#27;Zamknij\n\"Stworz katalog"
    "\n\"Stworz pod-datafile\n\"Stworz nowy data file\n\"Alle"
    "gro datafile\n\" OK \n\"#27;~Anuluj\n\"Data file zostal "
    "zapisany z nowym haslem._Czy stare powinno zostac "
    "usuniete?|Tak| Nie \n\"Data file zostal zapisany bez"
    " hasla._Czy stare powinno zostac usuniete?|Tak| Ni"
    "e \n\"Data file zostal zapisany z nowym haslem._Usun"
    "ac stare czy zatrzymac obydwa? |Zatrzymaj_obywda|U"
    "sun_stare\n\"Zapisz haslo\n\"Wlasciwosci data file\n\"Ha"
    "slo\n\"Usun liste hasel\n\"Aktualizuj obiekty\n\"(skalow"
    "ane)\n\"Pokaz pelny rozmiar\n\"obiekt data file\n\"Lista"
    " wlasciwosci\n\"New property\n\"tworzenie naglowka .h\n"
    "\"nazwa pliku:\n\"przegladaj...\n\"prefiks (opcja):\n\"Wy"
    "konaj\n\"Blad genereacji naglowka.|Zamknij\n\"Use this"
    "_palette\n\"Niezaimplementowana przegladarka\n\"Wybier"
    "z nazwe naglowka\n\"Wybierz\n\"Wlasciciel:\n\"Grupa:\n\"In"
    "ne:\n\"Odczyt\n\"Zapis\n\"Wykonywanie\n[formatletters\n\"D\n"
    "\"M\n\"Y\n\"h\n\"m\n\"s\n[graphini\n\"Nowe ust. ekranu\n\"Ustawi"
    "enia\n\"Info\n\"Dostepne tryby\n\"Aktualny tryb\n\"Wybrany"
    " tryb\n\"Ustaw\n\"Poprzednio wystapil blad z tym trybe"
    "m\n\"Sterownik:\n\"Allegro nie moze wykryc dostepnyvh "
    "trybow\n\"Wiecej prob\n\"#27;Zamknij\n[longdays\n\"Sunday"
    "\n\"Monday\n\"Tuesday\n\"Wednesday\n\"Thursday\n\"Friday\n\"Sa"
    "turday\n[longmonths\n\"January\n\"February\n\"March\n\"Apri"
    "l\n\"May\n\"June\n\"July\n\"August\n\"September\n\"October\n\"No"
    "vember\n\"December\n[obtext\n\"Blad - nie mozna otworzy"
    "c pliku %s.|#27;Kontynuuj\n[shortdays\n\"Sun\n\"Mon\n\"Tu"
    "e\n\"Wed\n\"Thu\n\"Fri\n\"Sat\n[shortmonths\n\"Jan\n\"Feb\n\"Mar\n"
    "\"Apr\n\"May\n\"Jun\n\"Jul\n\"Aug\n\"Sep\n\"Oct\n\"Nov\n\"Dec\n<hu>\n"
    "[clock\n\"\xd3ra be\xe1ll\xedt\xe1sai\n\"Alkalmaz\n\"M\xe1sodpercek mut"
    "at\xe1sa\n\"#27;Bez\xe1r\n[file_import_query\n\"Import\xe1lt obj"
    "ektum tulajdons\xe1gai\n\"N\xe9v:\n\"T\xedpus:\n\"Egyez\xf5 t\xedpusok\n"
    "\"Minden t\xedpus\n\"Import\xe1l\n\"Import\xe1l\xe1s kihagy\xe1sa\n\"Leg"
    "al\xe1""bb egy t\xedpust ki kell jel\xf6lni.| OK \n\"bet\xfbk csak"
    " 8 bites sz\xednm\xe9lys\xe9g\xfb""ek lehetnek.| OK \n\"Jelsz\xf3:\n\"#"
    "10; ~OK \n\"#27;~M\xe9gsem\n\"helytelen jelsz\xf3. Pr\xf3""b\xe1lja "
    "\xfajra| OK \n\"Jelsz\xf3lista t\xf6rl\xe9se\n\"Helyi ment\xe9s\n\"A l\xe9"
    "tez\xf5 (%s) objektumot friss\xedts\xfck, vagy \xfajat k\xe9sz\xedts"
    "\xfcnk?|Friss\xedt|\xdaj\n\"N\xe9v sz\xe9p\xedt\xe9se\n\"Relat\xedv \xfatvonal ha"
    "szn\xe1lata\n[filebrow\n\"Lemez eszk\xf6z:\n\"Mutat:\n\"#27;~M\xe9"
    "gsem\n\"\xc9rv\xe9nytelen f\xe1jl|~OK\n\"Kiv\xe1lasztva:\n\"Alk\xf6nyvt"
    "\xe1r k\xe9sz\xedt\xe9se\n\"Allegro data f\xe1jl k\xe9sz\xedt\xe9se\n\"#settin"
    "gs;Be\xe1ll\xedt\xe1sok\n\"Biztos benne,hogy el akarja t\xe1vol\xed"
    "tani a \"%s\" k\xf6nyvt\xe1rat (minden tartalma t\xf6rl\xe9sre k"
    "er\xfcl)?|Igen| Nem \n\"Biztos benne, hogy el akarja t\xe1"
    "vol\xedtani a \"%s f\xe1jlt?\".|Igen| Nem \n\"|Igen mindenre"
    "\n\"A lemez objektum elt\xe1vol\xedt\xe1sa nem siker\xfclt|Folyt"
    "at\xe1s\n\"%s egy k\xf6nyvt\xe1r|Bez\xe1r\xe1s\n\"%s nem k\xf6nyvt\xe1r|Bez"
    "\xe1r\xe1s\n\"%s nem l\xe9tezik. Pr\xf3""b\xe1lja \xfajra.|Bez\xe1r\xe1s\n\"%s m"
    "\xe1r l\xe9tezik, biztos benne?|Igen|M\xe9gsem\n\"%s m\xe1r l\xe9te"
    "zik, pr\xf3""b\xe1lja \xfajra|OK\n\"\xdaj f\xe1jl b\xf6ng\xe9sz\xf5 megnyit\xe1sa"
    "\n\"CGUI f\xe1jl kiv\xe1laszt\xf3\n\"CGUI f\xe1jlkezel\xf5\n\"OK\n\"Tulaj"
    "dons\xe1gok szerkeszt\xe9se\n\"F\xe1jl m\xe1sol\xe1s\n\"F\xe1jl kiv\xe1g\xe1s\n"
    "\"T\xf6rl\xe9s\n\"Beilleszt\xe9s\n\"Kiv\xe1laszt\n\"K\xe9p mutat\xe1sa\n\"El\xf5"
    "n\xe9zet\n\"Eredeti hely mutat\xe1sa\n\"M\xf3""dos\xedt\xe1si id\xf5 mutat"
    "\xe1sa\n\"M\xe9ret mutat\xe1sa\n\"Attributumok mutat\xe1sa\n\"Jogosu"
    "lts\xe1gok mutat\xe1sa\n\"Rejtett \xe9s rendszerf\xe1jlok mutat\xe1"
    "sa\n\"M\xe1sol\xe1si t\xe1r mutat\xe1sa\n\"Form\xe1zott nevek\n\"Nincs "
    "n\xe9v\n\"Hiba\xfczenet\n\"A k\xf6nyvt\xe1rlista hi\xe1nyos lehet ism"
    "eretlen hiba miatt|OK\n\"k\xf6nyvt\xe1r\n\"k\xf6nyvt\xe1rak\n\"f\xe1jl\n"
    "\"f\xe1jlok\n\"MB\n\"kB\n\"b\xe1jt\n\"Hely:\n\"M\xfbvelet\n\"Jelsz\xf3 be\xedr"
    "\xe1sa\n\"\n\"N\xe9v\n\"V\xe1ltoztatva\n\"M\xe9ret(k)\n\"Tulajd.\n\"\n\"N\xe9v\n"
    "\"V\xe1ltoztatva\n\"M\xe9ret(k)\n\"Jogosults\xe1g\n[filebuff\n\"Kij"
    "el\xf6l\xe9si t\xe1rol\xf3\n\"#27;Bez\xe1r\n\"T\xf6r\xf6l\n\"M\xf3""d hozz\xe1""ad\xe1sa\n\""
    "Az adott f\xe1jl m\xe1r l\xe9tezik, fel\xfcl\xedrjam?|Igen|Nem\n\"F"
    "\xe1jl olvas\xe1si hiba|Bez\xe1r\xe1s\n\"\xdaj f\xe1jl l\xe9trehoz\xe1si hib"
    "a|Bez\xe1r\xe1s\n\"A(z) %s k\xf6nyvt\xe1r elt\xe1vol\xedt\xe1sa nem siker"
    "\xfclt. Rendszer\xfczenet: %s|Bez\xe1r\n\"A(z) %s f\xe1jlt nem s"
    "iker\xfclt elt\xe1vol\xedtani. Rendszer\xfczenet: %s|Bez\xe1r\n\"A("
    "z) %s Allegro data f\xe1jl elem elt\xe1vol\xedt\xe1sa nem sike"
    "r\xfclt. Rendszer\xfczenet: %s|Bez\xe1r\n[filedial\n\"\xd6nnek ni"
    "ncs enged\xe9lye a jogosults\xe1gok v\xe1ltoztat\xe1s\xe1ra| OK \n"
    "\"Jelz\xf5k: \n\"Jogosults\xe1gok \n\"Lemez objektum szerkesz"
    "t\xe9se\n\"Hely:\n\"N\xe9v:\n\"M\xfbvelet\n\"M\xe9ret:\n\"Utolj\xe1ra v\xe1lto"
    "ztatva:\n\"Ismeretlen\n\"Forr\xe1s-n\xe9v:\n\"F\xe1jlt\xedpus:\n\"Alle"
    "gro dataf\xe1jl (k\xf6nyvt\xe1r)\n\"Allegro hangminta\n\"Allegr"
    "o midi f\xe1jl\n\"Allegro midi f\xe1jl\n\"Allegro anim\xe1""ci\xf3\n\""
    "Allegro k\xe9p\n\"Allegro sprite\n\"Allegro leford\xedtott s"
    "prite\n\"Allegro mode-x leford\xedtott sprite\n\"Allegro "
    "paletta\n\"Allegro bet\xfbt\xedpus\n\"Allegro bin\xe1ris f\xe1jl\n\""
    "Allegro felhaszn\xe1l\xf3i\n\"Allegro dataf\xe1jl\n\"K\xf6nyvt\xe1r\n\""
    "F\xe1jl\n\"K\xe9p\n\"Tulajdons\xe1gok\n\"~R (\xcdr\xe1sv\xe9""dett)\n\"~H (Rej"
    "tett)\n\"~S (Rendszer f\xe1jl)\n\"~A (Arch\xedv f\xe1jl)\n\"A tul"
    "ajdons\xe1g megv\xe1ltoztat\xe1sa nem siker\xfclt. Rendszer\xfcze"
    "net:\"%s\"|Bez\xe1r\n\"A tulajdons\xe1g megv\xe1ltoztat\xe1sa isme"
    "retlen okb\xf3l nem siker\xfclt.|Bez\xe1r\n\"T\xf6m\xf6r\xedt\xe9s:\n\"Semm"
    "i\n\"Egyedi\n\"Glob\xe1lis\n\"A megadott k\xf6nyvt\xe1rt nem sike"
    "r\xfclt l\xe9\xe1trehozni|#27;Bez\xe1r\n\"K\xf6nyvt\xe1r l\xe9trehoz\xe1s\n\"A"
    "l adat f\xe1jl l\xe9trehoz\xe1s\n\"\xdaj adatf\xe1jl l\xe9trehoz\xe1s\n\"Al"
    "legro dataf\xe1jl\n\" OK \n\"#27;~M\xe9gsem\n\"Az adatf\xe1jl elt"
    "\xe1rolva az \xfaj jelsz\xf3val._Az el\xf5z\xf5 jelsz\xf3t elfelejts"
    "em?|Igen| Nem \n\"Az adatf\xe1jl elt\xe1rolva jelsz\xf3 n\xe9lk\xfc"
    "l._Az el\xf5z\xf5 jelsz\xf3t elfelejtsem?|Igen| Nem \n\"Az ad"
    "atf\xe1jl elt\xe1rolva az \xfaj jelsz\xf3val._Az el\xf5z\xf5 jelsz\xf3t"
    " elfelejtsem, vagy legyen mindkett\xf5 a mem\xf3ri\xe1""ban?|"
    "Mindkett\xf5|Elfelejt\n\"Jelsz\xf3 helyi ment\xe9se\n\"Adat f\xe1j"
    "l tulajdons\xe1gok\n\"Jelsz\xf3\n\"Jelsz\xf3 lista t\xf6rl\xe9se\n\"Obj"
    "eltumok friss\xedt\xe9se\n\"(m\xe9retezett)\n\"Teljes m\xe9ret\n\"Ad"
    "atf\xe1jl objektum\n\"Tulajdons\xe1g lista\n\"\xdaj tulajdons\xe1g"
    "\n\"Fejl\xe9""c f\xe1jl gener\xe1l\xe1s\n\"F\xe1jl n\xe9v:\n\"Tall\xf3z...\n\"Mac"
    "ro prefix (esetleges):\n\"Gener\xe1l\n\"A gener\xe1l\xe1s nem s"
    "iker\xfclt.|Bez\xe1r\n\"Paletta alkalmaz\xe1sa\n\"Nincs megfele"
    "l\xf5 n\xe9z\xf5\n\"fejl\xe9""c f\xe1jl kiv\xe1laszt\xe1sa\n\"Kiv\xe1laszt\n\"Tula"
    "jdonos:\n\"Csoport:\n\"M\xe1s:\n\"Olvas\n\"\xcdr\n\"Futtet\n[format"
    "letters\n\"D\n\"M\n\"Y\n\"h\n\"m\n\"s\n[graphini\n\"\xdaj k\xe9perny\xf5 b"
    "e\xe1ll\xedt\xe1sok be\xedr\xe1sa\n\"Be\xe1ll\xedt\xe1sok\n\"Inf\xf3\n\"El\xe9rhet\xf5 m\xf3"
    "dok\n\"Jelenlegi m\xf3""d\n\"Kiv\xe1lasztott m\xf3""d\n\"M\xf3""d be\xe1ll\xedt\xe1"
    "sa\n\"El\xf5z\xf5 hib\xe1s m\xf3""d\n\"Grafikus meghajt\xf3:\n\"Allegro: "
    "nem siker\xfclt az el\xe9rhet\xf5 m\xf3""dokat felismerni \n\"tov\xe1"
    "bbi pr\xf3""b\xe1lkoz\xe1sok, miel\xf5tt\n\"#27;Bez\xe1r\n[longdays\n\"S"
    "unday\n\"Monday\n\"Tuesday\n\"Wednesday\n\"Thursday\n\"Frida"
    "y\n\"Saturday\n[longmonths\n\"January\n\"February\n\"March\n"
    "\"April\n\"May\n\"June\n\"July\n\"August\n\"September\n\"Octobe"
    "r\n\"November\n\"December\n[obtext\n\"Hiba a %s f\xe1jl megn"
    "yit\xe1s\xe1n\xe1l.|#27;Folytat\xe1s\n[shortdays\n\"Sun\n\"Mon\n\"Tue"
    "\n\"Wed\n\"Thu\n\"Fri\n\"Sat\n[shortmonths\n\"Jan\n\"Feb\n\"Mar\n\""
    "Apr\n\"May\n\"Jun\n\"Jul\n\"Aug\n\"Sep\n\"Oct\n\"Nov\n\"Dec\n<es>\n["
    "clock\n\"Ajustar configuraci\xf3n del reloj\n\"Aplicar\n\"M"
    "ostrar segundos\n\"#27;Cerrar\n[file_import_query\n\"Pr"
    "opiedades del objeto importado\n\"Nombre:\n\"Tipo:\n\"Ti"
    "pos_asociados\n\"Todos_los tipos\n\"Importar\n\"Saltar i"
    "mportaci\xf3n\n\"Debes seleccionar al menos un tipo.| A"
    "ceptar \n\"Las fuentes solo pueden usar una profundi"
    "dad de color de 8 bits.| Aceptar \n\"Introduce el pa"
    "ssword:\n\"#10; ~Aceptar \n\"#27;~Cancelar\n\"El passwor"
    "d introducido es incorrecto. Int\xe9ntalo de nuevo| A"
    "ceptar \n\"Limpiar lista de pwds\n\"Salvar local\n\"\xbfSe "
    "deben actualizar el objeto existente (%s), o se de"
    "be crear uno nuevo?|Actualizar|Nuevo\n\"Mejorar apar"
    "iencia del nombre\n\"Usar ruta relativa\n[filebrow\n\"U"
    "nidad:\n\"Mostrar:\n\"#27;~Cancelar\n\"Archivoilegal|~Ac"
    "eptar\n\"Seleccionado:\n\"Crear subdirectorio\n\"Crear a"
    "rchivo de datos de Allegro\n\"#settings;Configuraci\xf3"
    "n\n\"\xbf""Est\xe1s seguro de que quieres eliminar el direct"
    "orio \"%s\" (todo lo que est\xe9 guardado en \xe9l ser\xe1 el"
    "iminado)?|S\xed| No \n\"\xbf""Est\xe1s seguro de que quieres el"
    "iminar el archivo \"%s\"?|S\xed| No \n\"|S\xed a todo\n\"La el"
    "iminadi\xf3""c del objeto no se ha completado|Continuar"
    "\n\"%s es un directorio|Cerrar\n\"%s no es un director"
    "io|Cerrar\n\"%s no existe. Int\xe9ntalo de nuevo.|Cerra"
    "r\n\"%s ya existe, est\xe1s seguro?|S\xed|Cancelar\n\"%s ya "
    "existe, int\xe9ntalo de nuevo|Aceptar\n\"Abrir nuevo na"
    "vegador\n\"Selector de archivos de CGUI\n\"Gestor de a"
    "rchivos de CGUI\n\"Aceptar\n\"Editar propiedades\n\"Copi"
    "ar archivo\n\"Cortar archivo\n\"Eliminar\n\"Pegar\n\"Selec"
    "cionar\n\"Mostrar imagen\n\"Ventana de previsualizaci\xf3"
    "n\n\"Mostrar lugar original\n\"Mostrar tiempo de modif"
    "icaci\xf3n\n\"Mostrar tama\xf1o\n\"Mostrar atributos\n\"Mostra"
    "r permisos\n\"Mostrar archivos ocultos/de sistema\n\"M"
    "ostrar b\xfa""ffer de copia\n\"Nombres formateados\n\"Nombr"
    "e no presente\n\"Mensaje de error\n\"El listado del di"
    "rectorio puede estar incompleto debido a un error "
    "desconocido|Aceptar\n\"dir\n\"dirs\n\"arch\n\"archs\n\"MB\n\"k"
    "B\n\"bytes\n\"Direcci\xf3n:\n\"Acci\xf3n\n\"Introduce el passwor"
    "d\n\"\n\"Nombre\n\"Modificado\n\"Tama\xf1o(k)\n\"Atrib.\n\"\n\"Nomb"
    "re\n\"Modificado\n\"Tama\xf1o(k)\n\"Permisos\n[filebuff\n\"B\xfa""f"
    "fer de selecci\xf3n\n\"#27;Cerrar\n\"Limpiar\n\"Modo a\xf1""adir"
    "\n\"El archivo especificado ya existe, reemplazarlo?"
    "|S\xed|No\n\"Error al intentar leer el archivo|Cerrar\n\""
    "Error al intentar crear un nuevo archivo|Cerrar\n\"E"
    "l directorio %s no pudo ser eliminado. Mensaje del"
    " sistema: %s|Cerrar\n\"El archivo %s . Mensaje del s"
    "istema: %s|Cerrar\n\"El objeto del archivo de datos "
    "de Allegro %s no pudo ser eliminado. Mensaje del s"
    "istema: %s|Cerrar\n[filedial\n\"No se te permite camb"
    "iar los permisos| Aceptar \n\"Flags: \n\"Permisos \n\"Ed"
    "itar objeto de disco\n\"Direcci\xf3n:\n\"Nombre:\n\"Acci\xf3n\n"
    "\"Tama\xf1o:\n\"\xdaltima modificaci\xf3n:\n\"Desconocido\n\"Nombr"
    "e origen:\n\"Tipo de archivo:\n\"Archivo de datos de A"
    "llegro (directorio)\n\"Muestra de sonido de Allegro\n"
    "\"Archivo midi de Allegro\n\"Archivo midi de Allegro\n"
    "\"Animaci\xf3n de Allegro\n\"Imagen de Allegro\n\"Sprite d"
    "e Allegro\n\"Sprite compilado de Allegro\n\"Sprite com"
    "pilado modo-x de Allegro\n\"Paleta de Allegro\n\"Fuent"
    "e de Allegro\n\"Archivo binario de Allegro\n\"Definido"
    " por el usuario de Allegro\n\"Archivo de datos de Al"
    "legro\n\"Directorio\n\"Archivo\n\"Imagen\n\"Atributos\n\"~R "
    "(Protegido contra escritura)\n\"~H (Oculto)\n\"~S (Sis"
    "tema)\n\"~A (Archivo)\n\"El comando para cambiar los a"
    "trbutos fall\xf3. El mensaje del sistema es:\"%s\"|Cerr"
    "ar\n\"El comando para cambiar los atrbutos fall\xf3 por"
    " razones desconocidas.|Cerrar\n\"Empaquetado:\n\"Nada\n"
    "\"Individual\n\"Global\n\"El directorio especificado no"
    " se ha podido crear|#27;Cerrar\n\"Crear directorio\n\""
    "Crear sub-archivo de datos\n\"Crear nuevo archivo de"
    " datos\n\"Archivo de datos de Allegro\n\" Aceptar \n\"#2"
    "7;~Cancelar\n\"El archivo de datos se ha guardado co"
    "n el nuevo password._\xbf""Debe olvidarse el password a"
    "nterior?|S\xed| No \n\"El archivo de datos se ha guarda"
    "do sin password._\xbf""Debe olvidarse el password anter"
    "ior?|S\xed| No \n\"El archivo de datos se ha guardado c"
    "on el nuevo password._Debe olvidarse el password a"
    "nterior o deben dejarse en memoria ambos?|Mantener"
    " ambos|Olvidarlo\n\"Salvar password local\n\"Propiedad"
    "es del archivo de datos\n\"Password\n\"Limpiar lista d"
    "e pwds\n\"Actializar objectos\n\"(escalada)\n\"Mostrar t"
    "ama\xf1o completo\n\"Objeto de archivo de datos\n\"Lista "
    "de propiedades\n\"Nueva propiedad\n\"Generaci\xf3n del ar"
    "chivo de cabecera\n\"Nombre del archivo:\n\"Examinar.."
    ".\n\"Prefijo de la macro (opcional):\n\"Generar\n\"La ge"
    "neraci\xf3n de la cabecera fall\xf3.|Cerrar\n\"Usar paleta"
    "\n\"Visor no implementado\n\"Selecciona el nombre del "
    "archivo de cabecera\n\"Seleccionar\n\"Due\xf1o:\n\"Grupo:\n\""
    "Otro:\n\"Lectura\n\"Escritura\n\"Ejecuci\xf3n\n[formatletter"
    "s\n\"D\n\"M\n\"Y\n\"h\n\"m\n\"s\n[graphini\n\"Introduce la nueva "
    "configuraci\xf3n de pantalla\n\"Configuraci\xf3n\n\"Informac"
    "i\xf3n\n\"Modos disponibles\n\"Modo actual\n\"Modo seleccio"
    "nado\n\"Aplicar modo\n\"Fall\xf3 previamente con modo\n\"Dr"
    "iver gr\xe1""fico:\n\"Allegro fall\xf3 en la detecci\xf3n de mo"
    "dos de v\xed""deo\n\"mas intentos antes\n\"#27;Cerrar\n[long"
    "days\n\"Sunday\n\"Monday\n\"Tuesday\n\"Wednesday\n\"Thursday"
    "\n\"Friday\n\"Saturday\n[longmonths\n\"January\n\"February\n"
    "\"March\n\"April\n\"May\n\"June\n\"July\n\"August\n\"September\n"
    "\"October\n\"November\n\"December\n[obtext\n\"Error al abr"
    "ir el archivo %s.|#27;Continuar\n[shortdays\n\"Sun\n\"M"
    "on\n\"Tue\n\"Wed\n\"Thu\n\"Fri\n\"Sat\n[shortmonths\n\"Jan\n\"Feb"
    "\n\"Mar\n\"Apr\n\"May\n\"Jun\n\"Jul\n\"Aug\n\"Sep\n\"Oct\n\"Nov\n\"Dec"
    "\n<fr>\n[clock\n\"Ajuster la configuration de la montr"
    "e\n\"Apliquer\n\"Montrer segondes\n\"#27;Fermer\n[file_im"
    "port_query\n\"Propi\xe9t\xe9s de l'objet import\xe9\n\"Nom:\n\"Ty"
    "pe:\n\"Types_associ\xe9s\n\"Tous_les_types\n\"Importer\n\"Shu"
    "nter importation\n\"Vous devez choisir au moins un t"
    "ype.| Accepter \n\"Les polices ne peuvent utiliser q"
    "u'une profondeur de couleur de 8 bits.| Accepter \n"
    "\"Introduisez le mot de passe:\n\"#10; ~Accepter \n\"#2"
    "7; ~Annuler\n\"Le mot de passe introduit est incorre"
    "ct. Essayez \xe0 nouveau| Accepter \n\"Vider la liste d"
    "e mots de passe\n\"Sauvegarder local\n\"L'objet exista"
    "nt (%s) doit \xeatre actualis\xe9, ou doit-on en cr\xe9""er u"
    "n nouveau?|Actualiser|Nouveau\n\"Am\xe9liorer l'apparen"
    "ce du nom\n\"Utiliser chemin relatif\n[filebrow\n\"Disq"
    "ue:\n\"Montrer:\n\"#27;~Annuler\n\"Fichier illegal|~Acce"
    "pter\n\"Selectionn\xe9:\n\"Cr\xe9""er sous-r\xe9pertoire\n\"Cr\xe9""er f"
    "ichier de donn\xe9""es d'Allegro\n\"#settings;Configurati"
    "on\n\"Etes vous s\xfbr de voiloir \xe9liminer le r\xe9pertoir"
    "e\"%s\" (tout son contenu sera perdu)?|Oui| Non \n\"Et"
    "es vous s\xfbr de voiloir \xe9liminer le fichier\"%s\" ?|O"
    "ui| Non \n\"|Oui \xe0 tout\n\"L'\xe9limination de l'objet n'"
    "a pas \xe9t\xe9 compl\xe9t\xe9""e|Continuer\n\"%s est un r\xe9pertoir"
    "e|Fermer\n\"%s n'est pas un r\xe9pertoire|Fermer\n\"%s n'"
    "existe pas. Essayez \xe0 nouveau.|Fermer\n\"%s existe, "
    "\xeates vous s\xfbr?|Oui|Annuler\n\"%s existe, essayez \xe0 n"
    "ouveau|Accepter\n\"Ouvrir un nouveau navigateur\n\"Sel"
    "ecteur de fichiers de CGUI\n\"Manager de fichiers de"
    " CGUI\n\"Accepter\n\"Editer propri\xe9t\xe9s\n\"Copier fichier"
    "\n\"Couper fichier\n\"Eliminer\n\"Coller\n\"Selectionner\n\""
    "Montrer image\n\"Fen\xeatre de pr\xe9visualisation\n\"Montre"
    "r emplacement originel\n\"Montrer date de modificati"
    "on\n\"Montrer taille\n\"Montrer attributs\n\"Montrer dro"
    "its\n\"Montrer fichiers cach\xe9s/de syst\xe8me\n\"Montrer b"
    "uffer de copie\n\"Noms formatt\xe9s\n\"Nom non pr\xe9sent\n\"M"
    "essage d'erreur\n\"Le listing du r\xe9pertoire peut \xeatr"
    "e incomplet \xe0 cause d'une erreur inconnue|Accepter"
    "\n\"rep\n\"reps\n\"fich\n\"fichs\n\"Mo\n\"ko\n\"octets\n\"Addresse"
    ":\n\"Action\n\"Introduisez le mot de passe\n\"\n\"Nom\n\"Mod"
    "ifi\xe9\n\"Taille(k)\n\"Attrib.\n\"\n\"Nom\n\"Modifi\xe9\n\"Taille(k"
    ")\n\"Droits\n[filebuff\n\"Buffer de selection\n\"#27;Ferm"
    "er\n\"Vider\n\"Mode ajouter\n\"Le fichier specifi\xe9 exist"
    "e d\xe9j\xe0, le remplacer?|oui|Non\n\"Erreur en essayant "
    "de lire le fichier|Fermer\n\"Erreur en essayant de c"
    "r\xe9""er un nouveau fichier|Fermer\n\"Le r\xe9pertoire %s n"
    "'a pas pu \xeatre \xe9limin\xe9. Message du syst\xe8me: %s|Fer"
    "mer\n\"Le fichier %s n'a pas pu \xeatre \xe9limin\xe9. Messag"
    "e du syst\xe8me: %s|Fermer\n\"L'objet du fichier de don"
    "n\xe9""es d'Allegro %s n'a pas pu \xeatre \xe9limin\xe9. Message"
    " du syst\xe8me: %s|Fermer\n[filedial\n\"Vous n'\xeates pas "
    "autoris\xe9 \xe0 modifier les droits| Accepter \n\"Flags: "
    "\n\"Droits \n\"Editer objet de disque\n\"Adresse:\n\"Nom:\n"
    "\"Action\n\"Taille:\n\"Derni\xe8re modification:\n\"Inconnu\n"
    "\"Nom de source:\n\"Type d'archive:\n\"Fichier de donn\xe9"
    "es d'Allegro (rep\xe9rtoire)\n\"Extrait de son d'Allegr"
    "o\n\"Fichier midi d'Allegro\n\"Fichier midi d'Allegro\n"
    "\"Animation d'Allegro\n\"Image d'Allegro\n\"Sprite d'Al"
    "legro\n\"Sprite compil\xe9 d'Allegro\n\"Sprite compil\xe9 mo"
    "de-x d'Allegro\n\"Palette d'Allegro\n\"Police d'Allegr"
    "o\n\"Fichier binaire d'Allegro\n\"D\xe9""fini par l'utilisa"
    "teur d'Allegro\n\"Fichier de donn\xe9""es d'Allegro\n\"R\xe9pe"
    "rtoire\n\"Fichier\n\"Image\n\"Attributs\n\"~R (Proteg\xe9 con"
    "tre \xe9""criture)\n\"~H (Cach\xe9)\n\"~S (Syst\xe8me)\n\"~A (Archi"
    "ve)\n\"La commande pour modifier les attributs a \xe9""ch"
    "ou\xe9. Le message du syst\xe8me est:\"%s\"|Fermer\n\"La com"
    "mande pour modifier les attributs a \xe9""chou\xe9 pour de"
    "s raisons inconnues.|Fermer\n\"Pack\xe9:\n\"Rien\n\"Individ"
    "uel\n\"Global\n\"Le r\xe9pertoire sp\xe9""cifi\xe9 n'a pas pu \xeatr"
    "e cre\xe9|#27;Fermer\n\"Creer r\xe9pertoire\n\"Creer sous-fi"
    "chier de donn\xe9""es\n\"Creer nouveau fichier de donn\xe9""es"
    "\n\"Fichier de donn\xe9""es d'Allegro\n\" Accepter \n\"#27;~A"
    "nnuler\n\"Le fichier de donn\xe9""es a \xe9t\xe9 sauvegard\xe9 ave"
    "c le nouveau mot de passe._Le mot de passe pr\xe9""ceda"
    "nt doit-il \xeatre oubli\xe9?|Oui| Non \n\"Le fichier de d"
    "onn\xe9""es a \xe9t\xe9 sauvegard\xe9 sans mot de passe._Le mot "
    "de passe pr\xe9""cedant doit-il \xeatre oubli\xe9?|Oui| Non \n"
    "\"Le fichier de donn\xe9""es a \xe9t\xe9 sauvegard\xe9 avec le no"
    "uveau mot de passe._\xbfLe mot de passe pr\xe9""cedant doi"
    "t-il \xeatre oubli\xe9 ou sauvegard\xe9 avec le nouveau?|Ga"
    "rder les deux|L'oublier\n\"Sauvegarder le mot de pas"
    "se local\n\"Propi\xe9t\xe9s du fichier de donn\xe9""es\n\"Mot de "
    "passe\n\"Vider liste de mots de passe\n\"Actualiser ob"
    "jets\n\"(\xe0 l'\xe9""chelle)\n\"Montrer taille r\xe9""elle\n\"Objet "
    "de fichier de donn\xe9""es\n\"Liste de propi\xe9t\xe9s\n\"Nouvell"
    "e propi\xe9t\xe9\n\"Generation du fichier d'ent\xeate\n\"Nom du"
    " fichier:\n\"Examiner...\n\"Prefixe de la macro (optio"
    "nnel):\n\"G\xe9n\xe9rer\n\"La g\xe9n\xe9ration de l'ent\xeate a echou"
    "\xe9.|Fermer\n\"Utiliser palette\n\"Viseur non impl\xe9ment\xe9"
    "\n\"Selectionne le nom du fichier d'ent\xeate\n\"Selectio"
    "nner\n\"Propri\xe9taire:\n\"Groupe:\n\"Autre:\n\"Lecture\n\"Ecr"
    "iture\n\"Execution\n[formatletters\n\"D\n\"M\n\"Y\n\"h\n\"m\n\"s\n"
    "[graphini\n\"Introduisez la nouvelle configuration d"
    "'\xe9""cran\n\"Configuration\n\"Information\n\"Modes disponib"
    "les\n\"Mode actuel\n\"Mode selectionn\xe9\n\"Apliquer mode\n"
    "\"A \xe9""chou\xe9 pr\xe9""cedemment avec le mode\n\"Driver graphi"
    "que:\n\"Allegro a \xe9""chou\xe9 dans la d\xe9tection de modes "
    "de vid\xe9o\n\"d'autres essais pr\xe9""cedemment\n\"#27;Fermer"
    "\n[longdays\n\"Sunday\n\"Monday\n\"Tuesday\n\"Wednesday\n\"Th"
    "ursday\n\"Friday\n\"Saturday\n[longmonths\n\"January\n\"Feb"
    "ruary\n\"March\n\"April\n\"May\n\"June\n\"July\n\"August\n\"Sept"
    "ember\n\"October\n\"November\n\"December\n[obtext\n\"Erreur"
    " \xe0 l'ouverture du fichier %s.|#27;Continuer\n[short"
    "days\n\"Sun\n\"Mon\n\"Tue\n\"Wed\n\"Thu\n\"Fri\n\"Sat\n[shortmont"
    "hs\n\"Jan\n\"Feb\n\"Mar\n\"Apr\n\"May\n\"Jun\n\"Jul\n\"Aug\n\"Sep\n\"O"
    "ct\n\"Nov\n\"Dec\n<pt>\n[clock\n\"Ajustar a configura\xe7\xe3o d"
    "o rel\xf3gio\n\"Aplicar\n\"Exibir os segundos\n\"#27;Fechar"
    "\n[file_import_query\n\"Propriedades do objeto import"
    "ado\n\"Nome:\n\"Tipo:\n\"Tipos_Associados\n\"Todos_Tipos\n\""
    "Importar\n\"Pular importa\xe7\xe3o\n\"Voce deve selecionar p"
    "elo menos um tipo.| Aceitar\n\"As fontes podem usar "
    "somente 8 bits de profundidade.| Aceitar\n\"Entre co"
    "m a senha:\n\"#10; ~Aceitar \n\"#27;~Cancelar\n\"A senha"
    " informada esta incorreta. Tente novamente| Aceita"
    "r\n\"Limpar a lista de Pwds\n\"Salvar local\n\"Deseja at"
    "ualizar o objeto existente (%s) ou criar um novo?|"
    "Atualizar|Novo\n\"Deseja melhorar a apar\xeancia do nom"
    "e\n\"Usar caminho parecido\n[filebrow\n\"Unidade:\n\"Most"
    "rar:\n\"#27;~Cancelar\n\"Arquivo ilegal|~/Aceitar\n\"Sel"
    "ecionado:\n\"Criar sub-diret\xf3rio\n\"Criar arquivo de d"
    "ados do Allegro\n\"#configura\xe7\xf5""es;Configura\xe7\xf5""es\n\"Voc"
    "\xea realmente quer remover o diret\xf3rio \"%s\" (tudo qu"
    "e esta armazenado ser\xe1 deletado)?|Sim| N\xe3o \n\"Voc\xea "
    "realmente quer remover o arquivo\"%s\".|Sim| N\xe3o \n\"|"
    "Sim para todos\n\"A remo\xe7\xe3o do objeto do disco n\xe3o f"
    "oi completada|Continuar\n\"%s \xe9 um diret\xf3rio|Fechar\n"
    "\"%s n\xe3o \xe9 um diret\xf3rio|Fechar\n\"%s n\xe3o existe. Tent"
    "e novamente.|Fechar\n\"%s j\xe1 existe, voc\xea realmente "
    "est\xe1 certo dessa opera\xe7\xe3o?|Sim|Cancelar\n\"%s j\xe1 exi"
    "ste, por favor tente novamente|Aceitar\n\"Abrir novo"
    " navegador\n\"Selecionador de arquivos CGUI\n\"Gestor "
    "de arquivos CGUI\n\"Aceitar\n\"Editar propriedades\n\"Co"
    "piar arquivo\n\"Recortar arquivo\n\"Deletar\n\"Colar\n\"Se"
    "lecionar\n\"Mostrar imagem\n\"Janela de pr\xe9-visualiza\xe7"
    "\xe3o\n\"Mostrar lugar original\n\"Mostrar data de atuali"
    "za\xe7\xe3o\n\"Mostrar tamanho\n\"Mostrar atributos\n\"Mostrar"
    " permiss\xf5""es\n\"Mostrar arquivos ocultos/de sistema\n\""
    "Mostrar buffer de c\xf3pia\n\"Nomes formatados\n\"Nenhum "
    "nome presente\n\"Mensagem de erro\n\"A lista do diret\xf3"
    "rio pode estar incompleta devido a um erro desconh"
    "ecido|Aceitar\n\"diret\xf3rio\n\"diret\xf3rios\n\"arquivo\n\"arq"
    "uivos\n\"MB\n\"kB\n\"bytes\n\"Localiza\xe7\xe3o:\n\"A\xe7\xe3o\n\"Entre co"
    "m a senha\n\"\n\"Nome\n\"Modificado\n\"Tamanho(k)\n\"Atribut"
    "o\n\"\n\"Nome\n\"Modificado\n\"Tamanho(k)\n\"Permiss\xf5""es\n[fil"
    "ebuff\n\"Buffer de sele\xe7\xe3o\n\"#27;Fechar\n\"Limpar\n\"Adic"
    "ionar modo\n\"O arquivo especificado j\xe1 existe, sobr"
    "escrever o mesmo?|Sim|N\xe3o\n\"Erro enquanto tenta ler"
    " o arquivo|Fechar\n\"Erro enquanto tenta criar um no"
    "vo arquivo|Fechar\n\"O diret\xf3rio %s n\xe3o pode ser rem"
    "ovido. Mensagem do sistema: %s|Fechar\n\"O arquivo %"
    "s n\xe3o pode ser removido. Mensagem do sistema: %s|F"
    "echar\n\"O objeto do arquivo de dados do Allegro %s "
    "n\xe3o pode ser removido. Mensagem do sistema: %s|Fec"
    "har\n[filedial\n\"Voc\xea n\xe3o possui permiss\xe3o para muda"
    "r as permiss\xf5""es| Aceitar\n\"Flags: \n\"Permiss\xf5""es \n\"Ed"
    "itar objeto de disco\n\"Localiza\xe7\xe3o:\n\"Nome:\n\"A\xe7\xe3o\n\"T"
    "amanho:\n\"\xdaltima mudan\xe7""a em:\n\"Desconhecido\n\"Nome de"
    " Origem:\n\"Tipo de arquivo:\n\"Arquivo de dados do Al"
    "legro (diret\xf3rio)\n\"Amostra de som do Allegro\n\"Arqu"
    "ivo midi do Allegro\n\"Arquivo midi do Allegro\n\"Anim"
    "a\xe7\xe3o do Allegro\n\"Imagem do Allegro\n\"Sprite do Alle"
    "gro\n\"Aprite compilado do Allegro\n\"Sprite compilado"
    " modo-x do Allegro\n\"Paleta do Allegro\n\"Fonte do Al"
    "legro\n\"Arquivo bin\xe1rio do Allegro\n\"Definido por um"
    " usu\xe1rio do Allegro\n\"Arquivo de dados do Allegro\n\""
    "Diret\xf3rio\n\"Arquivo\n\"Imagem\n\"Atributos\n\"~R (Protegi"
    "do contra escrita)\n\"~H (Oculto)\n\"~S (Arquivos de s"
    "istema)\n\"~A (Arquivo)\n\"O comando para mudar o atri"
    "buto falhou. A mensagem do sistema \xe9:\"%s\"|Fechar\n\""
    "O comando para mudar o atributo falhou por raz\xf5""es "
    "desconhecidas.|Fechar\n\"Empacotado:\n\"Nada\n\"Individu"
    "al\n\"Global\n\"N\xe3o se poude criar o diret\xf3rio especif"
    "icado|#27;Fechar\n\"Criar diret\xf3rio\n\"Criar sub-arqui"
    "vo de dados\n\"Criar novo arquivo de dados\n\"Arquivo "
    "de dados do Allegro\n\" Aceitar \n\"#27;~Cancelar\n\"O a"
    "rquivo de dados foi armazenado com a nova senha. D"
    "eseja desfazer-se da senha anterior|Sim| N\xe3o\n\"O ar"
    "quivo de dados foi armazenado sem senha. Deseja de"
    "sfazer-se da senha anterior|Sim| N\xe3o\n\"O arquivo de"
    " dados foi armazenado com a nova senha. Deseja des"
    "fazer-se da senha anterior ou deseja manter ambos "
    "em mem\xf3ria?|Manter ambos|Desfazer-se dela\n\"Salvar "
    "senha local\n\"Propriedades do arquivo de dados\n\"Sen"
    "ha\n\"Limpar lista de Pwds\n\"Atualizar objetos\n\"(esca"
    "lada)\n\"Visualizar todo o tamanho\n\"Objeto do arquiv"
    "o de dados\n\"Lista de propriedades\n\"Nova propriedad"
    "e\n\"Gera\xe7\xe3o do arquivo de cabe\xe7""alho\n\"Nome do arquiv"
    "o:\n\"Navegador...\n\"Prefixo da macro (opcional)\n\"Ger"
    "ar\n\"A gera\xe7\xe3o falhou.|Fechar\n\"Usar paleta\n\"Visuali"
    "zador n\xe3o implementado\n\"Selecione o nome do arquiv"
    "o de cabe\xe7""alho\n\"Selecionar\n\"Propriet\xe1rio:\n\"Grupo:\n"
    "\"Outro:\n\"Ler\n\"Escrever\n\"Executar\n[formatletters\n\"D"
    "\n\"M\n\"A\n\"h\n\"m\n\"s\n[graphini\n\"Entre com a nova config"
    "ura\xe7\xe3o de v\xed""deo\n\"Configura\xe7\xf5""es\n\"Informa\xe7\xf5""es\n\"Modos"
    " dispon\xedveis\n\"Modo atual\n\"Modo selecionado\n\"Aplica"
    "r modo\n\"Falhou previamente com modo\n\"Driver gr\xe1""fic"
    "o:\n\"Allegro falhou na detec\xe7\xe3o dos modos de v\xed""deo "
    "dispon\xedveis\n\"mais tentativas antes\n\"#27;Fechar\n[lo"
    "ngdays\n\"Domingo\n\"Segunda\n\"Ter\xe7""a\n\"Quarta\n\"Quinta\n\"S"
    "exta\n\"S\xe1""bado\n[longmonths\n\"Janeiro\n\"Fevereiro\n\"Mar\xe7"
    "o\n\"Abril\n\"Maio\n\"Junho\n\"Julho\n\"Agosto\n\"Setembro\n\"Ou"
    "tubro\n\"Novembro\n\"Dezembro\n[obtext\n\"Erro abrindo o "
    "arquivo %s.|#27;Continuar\n[shortdays\n\"Dom\n\"seg\n\"Te"
    "r\n\"Qua\n\"Qui\n\"Sex\n\"S\xe1""b\n[shortmonths\n\"Jan\n\"Fev\n\"Mar\n"
    "\"Abr\n\"Mai\n\"Jun\n\"Jul\n\"Ago\n\"Set\n\"Out\n\"Nov\n\"Dez\n";



DATAFILE cgui_labels[] = {
    { &cgui_cguilabl, DAT_ID('D', 'A', 'T', 'A'), 32545, cgui_cguilabl_prop },
    { 0, DAT_END, 0, 0 }
};



#ifdef ALLEGRO_USE_CONSTRUCTOR
CONSTRUCTOR_FUNCTION(static void _construct_me(void));
static void _construct_me(void)
{
    _construct_datafile(cgui_labels);
}
#endif



/* end of src/labldata.c */



